### ISSUE TITLE
VMM SDN GW

### ISSUE THREAD

**Issue by shedeed101** [Microsoft/SDN#106]
i have installed the SDN gateway template and peering it with Microsoft windows server acting as router

the problem is after fresh install the public IP address of the gateway doesn't show up on the windows router when using "Get-BgprouteInformation -type all"

i can see all the ip addresses used except for 2 

1- GW Public IP address
2- VIP created from "CreateTenantVIP-Custom"

this is the first part of the problem 

i have managed to resolve the first one by changing the gateway public ip address for example from 10.10.10.99 to 10.10.10.80 , after that it shows on the "Get-BgprouteInformation -type all"

but if i change the address from 10.10.10.80 to any thing and try to use the 10.10.10.80 ip address again, i get the same problem 
and i can never use the same ip address after changing it, altho its not showing as used on the ippool if the logical network 

the 2nd part of the problem is after deploying the GW template and configure a vm network to use it, i try to connect to it from any computer "domain joined or not" i get an error 

if i am connecting from windows server with  routing and remote access role i get 
" an error occured during the connection of the interface.
Policy match error"

Note: i have not done any changes to the default template settings 

and if i am connecting from any other computer from vpn wizard i get error "809" 

i am thinking this could be nps issue not sure tho,

Note: i am following this guide " https://blogs.technet.microsoft.com/larryexchange/2016/06/01/step-by-step-for-deploying-a-sdnv2-using-vmm-part-4/ " step by step

**Comment by AnirbanPaul** [comment]
Hi
The connection error indicates some kind of configuration mismatch between the two RAS servers. As a first step, can you provide us the following:
1. On the SDN side, please provide the output of Get-NetworkControllerVirtualGateway -ConnectionUri <REST uri>|ConvertTo-Json -Depth 10
2. On the on-prem side, please provide the output of "get-vpns2sinterface | fl *" from the RAS gateway.

**Comment by khsoong** [comment]
I have setup SDN GW using scvmm. Setup up S2S GRE & S2S IPSEC with no connectivity from VM subnet.
Had setup Network controller and SLB successfully.

I realised that HNV ip address was not assigned to the GW after priovisioning. The GW has only MGMT and Transit ip been allocated. The question now is do I allocate HNV ip to the GW manually or do I leave it as 169.xxx.xxx.xxx.xxx. Please advise. Thank yuou.

**Comment by AnirbanPaul** [comment]
Have you setup any tenant S2S/GRE connections? The HNV IP address does not get assigned till you provision a tenant gateway connection, as the tenant gateway compartment is created at that time

**Comment by khsoong** [comment]
I have setup the tenant gateway using service template and also a s2s gre but i can't access the remote web server page.

There are 3 nic to my tenant gateway, mgmt, transit ip are assigned automatically. But the hnv ip is having 169.xxx.xxx


Sent from my iPhone

On 8 Aug 2017, at 1:30 AM, Anirban Paul <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you setup any tenant S2S/GRE connections? The HNV IP address does not get assigned till you provision a tenant gateway connection, as the tenant gateway compartment is created at that time

**Comment by AnirbanPaul** [comment]
Can you send the output of the following commands:


  1.  Get-NetworkControllerGateway -ConnectionUri https://<REST uri of your deployment> | ConvertTo-Json -Depth 10
  2.  Get-NetworkControllerVirtualGateway -ConnectionUri https://<REST uri of your deployment> | ConvertTo-Json -Depth 10

Also, please send information about the remote IP you are trying to reach.

As far as the 169 address is concerned, you will find the correct IP on the compartment. If you run ipconfig /allcompartments, you will find the internal IP address plumbed there.

Thanks
Anirban

**Comment by khsoong** [comment]
Managed to setup everything using VMMExpress Script successfully !
Thanks Paul.

**Comment by grcusanz** [comment]
@shedeed101 have you resolved your issue?  Let us know so we can help and close this issue.  Thanks!

**Comment by grcusanz** [comment]
No further updates, so closing this issue.
