### ISSUE TITLE
Increasing number of vm networks?

### ISSUE THREAD

**Issue by Bearcomtech** [Microsoft/SDN#108]
Hi,

I now have a full and working deployment of the new sdn. When I check in vmm and create a vm network I can see that my sdn has a max of 50 vm networks? This will run out fast. How do I increase this number to let’s say 500 networks?

Best Regards.

**Comment by AnirbanPaul** [comment]
Hi
You must have seen this screen on the Connectivity page for VM network creation. Please ignore this for now. The number is incorrect, we will change this shortly. This number signifies the number of VM networks that can be supported by a SDN gateway. Today, each gateway can easily support more than 50 VM networks. So, if you have deployed 3 gateways, with 2 in active mode and 1 in standby mode, they will easily be able to support 150 VM networks. And if you need more than that, you can add more gateways to your gateway pool to increase the capacity.
Let me know if that answers your question.

Thanks
Anirban

**Comment by Bearcomtech** [comment]
Hi

Thank you for answering AnirbanPaul.
Yes, the values I talk about is on the connectivity page of a vm network in vmm. However, I am not 100% sure we talk about the same thing or same kind of setup.

On the connectivity page there is 2 type of numbers. VM networks and VPN gateways.
As I understand the “vm networks” number are related to network controllers and/or SLB/MUX when you turn on nat or routing.  “vpn gateways” number are related to Gateway machines when you setup vpn connections. So, when you talk about SDN gateway you confuse me a bit since it is the network controllers and slb/mux that I am worried about. When it comes to vpn connections the number is 250 which is fine for now.

You say that I can ignore this number but what happens when it runs to zero? Is the number just for show or does it have any impact on functionality at this stage?

Sorry for my strange questions.
Regards

**Comment by AnirbanPaul** [comment]
"VM Networks" on this page is specifically related to VPN gateways. The VPN gateways are multi-tenant, so each gateway will have connections for multiple tenants. The "VM networks" number specifies the number of tenants that can be supported per VPN gateway service. 
I know that we have increased this number in a recent update. I will provide an update tomorrow regarding this change and also whether there is any impact if the number goes down to 0.

**Comment by Bearcomtech** [comment]
Hi,

Thank you for information. So this number is decreasing when i turn on NAT beacause it creates a gateway subnet at the same time? which in turn is related to the gateway machines?

What i mean is that SDNv2 has 3 components.
Network controller, that provides VM networks to virtual machines with vxlan.
Loadbalancer / Mux, provides NAT and direct routing
Gateways, which provides VPN and GRE functionallity

When i enable nat on a network the Gateway component is not used(?). Why is the vm network number related to VPN gateways when i dont use the functions?


Anyway i look forward to update regarding the change and impact.
Best regards,

**Comment by AnirbanPaul** [comment]
Hi
So, you are correct that when the number goes to 0, you will not be able to add new connections. But, if you install the latest SCVMM update (Update Rollup 3), you will see that this number has been increased to 550. We are also going to make this configurable in the next update.
Thanks
Anirban

**Comment by Bearcomtech** [comment]
Hi AnirbanPaul,

Thank you very much for your information. It was helpful.

Regards,

**Comment by Bearcomtech** [comment]
Hi,

I Just upgraded to UR3 but i still only see 50 as max under the VM networks.

**Comment by sanjkum** [comment]
@Bearcomtech with UR3 of VMM the maximum number of VM Network still remains 50, but the number of VM subnet has increased. We are in process of providing a way to overwrite these default values and it will be shipped as part of UR4. In case, if this is a blocking issue as of now we will workout to provide you with a hotfix for the same. Please let me know if it is ok for you to wait till UR4 release.

**Comment by Bearcomtech** [comment]
@sanjkum
Thank you for your reply. It is not a critical thing right now so i can wait a few months. I just like to be prepared. Is there any planned ETA on UR4?

**Comment by sanjkum** [comment]
@Bearcomtech 
Thank You for your confirmation. I will update you as soon as the dates for UR4 release is finalized.

**Comment by sanjkum** [comment]
@Bearcomtech could you please close this issue if your queries are answered.

**Comment by Bearcomtech** [comment]
Hi,
Closing this thread on request. Thank you everyone for answers.

**Comment by eponerine** [comment]
I have just deployed SDNv2 with SCVMM 2019 and still see 50 as the number of VM Gateways allowed.

How do I tune this? What value/registry key/PoSH blackmagic must be performed?

**Comment by AnirbanPaul** [comment]
[+Sanjeev]
Sanjeev, can someone in the VMM Team take this one?

Thanks
Anirban

**Comment by sanjkum** [comment]
Following document explains how to change the default settings:

https://docs.microsoft.com/en-us/system-center/vmm/sdn-gateway?view=sc-vmm-2019#gateway-limits

Thank You,
Sanjeev

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by eponerine** [comment]
Perfect, thank you for the documentation to confirm it is supported!
