### ISSUE TITLE
SLB Public VIP No Response

### ISSUE THREAD

**Issue by khsoong** [Microsoft/SDN#111]
1. Deployed network controller (in a lab and all within a single host) and it is working. 2 VMs on different subnets within the same VM network can communicate with each other.

2. Configured SLB VM in SCVMM through service template. Other configurations like BGP, VIP Template and VIP PowerShell were done.

However, there is no response when I access the Public VIP on RRAS Server. When I access the Private VIP, I was redirected to the Public VIP. I have done most troubleshooting steps and all seem fine. My symptoms are similar to this thread:
https://social.technet.microsoft.com/Forums/SharePoint/en-US/989960e3-5c6f-4dc9-9695-6da5d1e81aab/sdn-cannot-connect-to-slbmux?forum=ws2016

What am I still missing, can someone please help? Thank you.

**Comment by andersonshen** [comment]
Hello Sir, how did you manage to resolve the issues?

**Comment by khsoong** [comment]
Yes, issue resolved ! If your setup proper, you should be able to access it via RRAS,

**Comment by andersonshen** [comment]
thanks first. Can you point out that those configurations are wrong?

**Comment by khsoong** [comment]
you need to provide me more details before I can help.
What setup did you use?

**Comment by andersonshen** [comment]
I follow blog to deploy as below https://blogs.technet.microsoft.com/larryexchange/2016/05/31/step-by-step-for-deploying-a-sdnv2-using-vmm-part-3/#comment-585 and http://davidfleming.org/2017/04/27/deploy-and-configure-sdn-software-load-balancer-service/#comment-307

**Comment by andersonshen** [comment]
Please advise! thanks.

**Comment by andersonshen** [comment]
Hello, Could you private VMMExpress of Fabricconfig file to me, I want to learn from you, how to use VMMExpress to deploy, thanks a lot!

**Comment by khsoong** [comment]
Hi Anderson, do you still require help?
Drop me a msg at keith.soong@hotmail.com, cheers.
