### ISSUE TITLE
TimeZone setting

### ISSUE THREAD

**Issue by richsmif** [Microsoft/SDN#119]
When deploying by script, there is no ability to set time zone.  All my VMs are pacific time, and should be GMT.  Not a show stopper as I can use GPO\Manual to change but would be nice.

**Comment by grcusanz** [comment]
I checked in an update to SDNExpress to use host time settings by default, with an optional manual override in the FabricConfig.psd1.  If using VMMSDNExpress instead, you will need to modify the service template for each of the components (NC, SLB, GW) to specify the desired time zone.
