### ISSUE TITLE
VMM SDN express script fails after NC deployment

### ISSUE THREAD

**Issue by blake-thompson** [Microsoft/SDN#120]
At first the script seems to work well. It deploys the network controllers and once that is done it then removes them again with the following error:

Error (21426)
Execution of :: on the configuration provider  failed. Detailed exception: Unable to connect to the network service. Check connection string and network connectivity. Execution of Microsoft.SystemCenter.NetworkService::OpenDeviceConnectionEx on the configuration provider 3e2875a7-5831-4fb2-b388-1672e1c20fee failed. Detailed exception: Microsoft.VirtualManager.NCRestApiWrappers.NCRestApiWrappersException
Check the documentation for the configuration provider or contact the publisher support.
Unable to connect to the network service. Check connection string and network connectivity.

Recommended Action
Check the documentation for the configuration provider or contact the publisher support.

Any help would be appreciated. Thx

**Comment by krisjturn** [comment]
Did you get this resolved?

**Comment by blake-thompson** [comment]
Yes thank you, we managed to get the SDN working

Met vriendelijke groet,
Blake Thompson
Senior Business consultant
Mobiel: +31 (0)641562399
E-mail: b.thompson@vcd.nl<mailto:b.thompson@vcd.nl>
Werkzaam op: maandag, dinsdag, woensdag, donderdag en vrijdag
[Logo_VCD_IS_e-mailhandtekening]
VCD Infra Solutions
Eemsgolaan 17, 9727 DW Groningen
Postbus 917, 9700 AX  Groningen
Tel: +31 (0)88 5975500
www.vcd.nl<http://www.vcd.nl/>
VCD heeft vestigingen in Groningen, Eindhoven en Delft.
Deze e-mail en begeleidende documenten kunnen vertrouwelijke informatie bevatten. Indien u niet de geadresseerde bent, is iedere openbaring, vermenigvuldiging, verspreiding en/of enige andere actie gerelateerd aan de inhoud van deze e-mail, strikt verboden. Indien u deze e-mail abusievelijk ontvangt verzoeken wij u direct telefonisch contact op te nemen met VCD Infra Solutions, telefoonnummer 088 5975500.

**Comment by btnhd** [comment]
How did you get it resolved?

Thank you

**Comment by blake-thompson** [comment]
The image was not up-to-date enough so when we tried to install it would time out and when I checked the teams config file they had made a couple of mistakes



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by nnamuhcs** [comment]
Thanks for the update.

**Comment by nick8880** [comment]
Hi blake-thompson,

I have followed your method to updated the OS to latest version and run the VMM SDN Express again, but i still seeing the same error, do you mind what else you have configured to fix the problem? Thanks
