### ISSUE TITLE
VMM SDN Express - Placement failed for Service Deployment

### ISSUE THREAD

**Issue by krisjturn** [Microsoft/SDN#124]
When running the VMM SDN Express script it stops with an error Placement failed for Service Deployment.  Within the VMMExpressLogfile.log the last line recorded is Starting Service Template Configuration getting Management Network [ ]

Within VMM, the last job ran shows Completed called Update placement of a service.  I also see the Service Template and the Service Deployment Configuration that was created for the NC.  

Not really sure where to troubleshoot at this point>?

**Comment by krisjturn** [comment]
I am not sure if this helps with troubleshooting but digging around the NC Service Deployment Configuration I have the following errors that seem to be related to storage?  It can't place these machines because of no suitable host?  The Rating Explanation has an error "The host does not have access to sufficient storage of the requested classification for one or more virtual disk associated with virtual machine "SDN-NCVM01."  On my configuration I don't have a Storage Classification called out I left that blank.

**Comment by krisjturn** [comment]
Added the Storage Classification and got a little past now.  Now it failing at Create Account.

**Comment by krisjturn** [comment]
The script now gets to the point where Creates Service Instance.  I see that all the network controllers are built.  It fails when it tries to invoke the script that is installing  Pre_Install_1?

**Comment by DNigussie** [comment]
@kristopherjturner What was the fix for it? Were you able to configure it all? 

Thanks

**Comment by kristopherjturner** [comment]
I honestly can't remember what we did or didn't do. Sorry.
