### ISSUE TITLE
SDNExpress needs to reboot Gateway VM after RemoteAccess installation on Server Core

### ISSUE THREAD

**Issue by nwoodmsft** [Microsoft/SDN#126]
On Server Core installations we are seeing the following issue:

> VERBOSE: [S7-MTGW-02]:                            [[WindowsFeature]RemoteAccess] Installation succeeded.
> VERBOSE: [S7-MTGW-02]:                            [[WindowsFeature]RemoteAccess] Successfully installed the feature
> RemoteAccess.
> VERBOSE: [S7-MTGW-02]:                            [[WindowsFeature]RemoteAccess] The Target machine needs to be
> restarted.
> VERBOSE: [S7-MTGW-02]: LCM:  [ End    Set      ]  [[WindowsFeature]RemoteAccess]  in 27.4640 seconds.
> VERBOSE: [S7-MTGW-02]: LCM:  [ End    Resource ]  [[WindowsFeature]RemoteAccess]
> VERBOSE: [S7-MTGW-02]:                            [] A reboot is required to progress further. Please reboot the
> system.
> WARNING: [S7-MTGW-02]:                            [] A reboot is required to progress further. Please reboot the
> system.

This is causing a subsequent step (putting port profiles for the gateway nics) to fail. It looks like the SDNExpress script needs to handle a reboot operation for the gateway VMs after RemoteAccess is installed.

**Comment by grcusanz** [comment]
Resolved this in last week's update for Windows Server, Version 1709.
