### ISSUE TITLE
Broadcast storm after install

### ISSUE THREAD

**Issue by blake-thompson** [Microsoft/SDN#134]
After much work we finally got the the entire stack in and working. We got an established status with the BGP peering so everything went well. Unfortunately after about 1 minute the network started dropping in what appears to be a broadcast storm. We cant figure out why this would be. does anyone have an idea how this could occur?

**Comment by grcusanz** [comment]
Hi, do you have any machines with the Microsoft Network Load Balancer (NLB) role installed on the same VLAN as the Mux?  We have seen reports of this when the two exist on the same VLAN.  If so the recommendation is to keep NLB on a separate segment.

**Comment by grcusanz** [comment]
@blake-thompson Hi Blake, do you need additional assistance with this issue?  Let us know, otherwise we will close this in a few days.  Thanks!

**Comment by grcusanz** [comment]
Closing issue since no update.
