### ISSUE TITLE
Changing Network Controller Cert breaks service fabric cluster after old certificate is removed

### ISSUE THREAD

**Issue by rhochmayr** [Microsoft/SDN#146]
Hi there

just encountered an issue after changing the network Controller certificates. I issued a new certificate and updated it on the Network Controller Nodes according to following blog post:

https://blogs.technet.microsoft.com/wsnetdoc/2017/08/25/sdn-troubleshooting-udp-communication-and-changing-network-controller-cert

1. Imported Cert with private key on all NC nodes
2. Executed "Set-NetworkController -ServerCertificate $cert" on one of the nodes
3. updated SSL bindings on remaining nodes via netsh http command

So far everything was working fine. Things stopped working once I removed the old certificate and rebooted the nodes. After that the service fabric could not be started anymore.

The "Service Fabric Host Service" and "Service Fabric Installer Service" weren't able to start.

The Microsoft-Service Fabric/Admin eventlogs showed following Errors:

Event ID: 58368 
System.Fabric.FabricDeployer.ClusterManifestValidationException: Cluster manifest validation failed with exception System.InvalidOperationException: Decryption failed. Error:-2146885620

Event ID: 59648
Decryption failed. StoreLocation: My, EncryptedString: ......

Upon inspecting the following Fabric Cluster Manifest I found the old Certificate Thumbprint was still used to decrypt the encrypted Passwords stored in the config files.

\\NCNode01\c$\ProgramData\Microsoft\Service Fabric\NCNode01.domain.com\Fabric\ClusterManifest.10.1.0.0.xml

The same goes for ClusterManifest.current.xml

At the end is a section that was still showing the old thumbprint:

Certificates
SecretsCertificate X509FindValue="OLD THUMBPRINT"
Certificates

Once I imported the old Certificate into the stores on the NC Nodes the services started fine again.

Can this be changed or updated to the new certificate as well or does the old certificate needs to stay in place? 

In our case the new Cert carries the same subject name as the old one but has been issued with a longer validity period. Not sure if having two certificates with the same subject name in the store will cause any issues further down the road. 

I read somewhere that this certainly can be an issue if the Hyper-V Nodes have multiple certs with the same name in their stores.

Many thanks & best regards,
Robert

**Comment by AnirbanPaul** [comment]
Hi
After updating the cert, when you execute the command "netsh http show sslcert" on all the NC Nodes, do you see the new certificate or the old certificate?

Multiple certs should not be an issue on the NC nodes, as NC is binding to a specific certificate.

Thanks
Anirban

**Comment by rhochmayr** [comment]
Hi Paul

thanks for your reply. Yes, the SSL bindings where showing the new certificate thumbprint on all three NC nodes when checking with the "netsh http show sslcert" command. 

The issue however seemed that the ClusterManifest XMLs still had the old thumprint for the "SecretsCertificate X509FindValue" field. The Manifests are located here on the NC nodes: 
"C:\ProgramData\Microsoft\Service Fabric\NCNode.domain.com\Fabric\"

The XML contains a few PasswordSecrets and I assume the certificate is used to decrypt those?
FileStoreService\PrimaryAccountNTLMPasswordSecret
FileStoreService\SecondaryAccountNTLMPasswordSecret
FileShareWinFabEtw\Password
FileShareWinFabCrashDump\Password
FileShareWinFabPerfCtr\Password

At least thats what it looked like according to the eventlogs when the service fabric services where trying to start

Event ID: 58368
System.Fabric.FabricDeployer.ClusterManifestValidationException: Cluster manifest validation failed with exception System.InvalidOperationException: Decryption failed. Error:-2146885620

Event ID: 59648
Decryption failed. StoreLocation: My, EncryptedString: ......

Once i put the old certificate into the personal store on the nodes the services where able to start again.

I found following link in regards to SF Secrets but I don't know whether they should be updated as part of the Set-NetworkController commandlet or if this requires manual work. 
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-secret-management

Thanks
Robert

**Comment by AnirbanPaul** [comment]
Hi
Can you also change the CredentialEncryptionCertificate to the new one. You can do that using the following cmdlet:
Set-NetworkControllerCluster -CredentialEncryptionCertificate <newCertObject>.

Once you have changed both the ServerCertificate (using the steps you followed before) and the CredentialEncryptionCertificate, please check if things work fine after you remove the old cert.

Thanks
Anirban

**Comment by rhochmayr** [comment]
Hi Anirban

thanks for the update.

Running the command "Set-NetworkControllerCluster -CredentialEncryptionCertificate <newCertObject>" did update the certificate used in the cluster manifests. The SF services are now starting but the NC service still ended up in a non working state. 

The command Set-NetworkControllerCluster finished without any errors and the certificate as well as the secrets in the manifest got updated with the new thumprint and base-64 strings so that part seems to be fine.

Eventlogs show following warnings now:
_Event ID: 28161
ParseConfigSettings: ErrorCode=E_FAIL, FileName=C:\ProgramData\Microsoft\Service Fabric\FabricHostSettings.xml_

_Event ID: 28161
ParseServicePackage: ErrorCode=E_FAIL, FileName=C:\ProgramData\Microsoft\Service Fabric\NCNode01.domain.com\Fabric\Fabric.Package.current.xml_

I will re-deploy the SDN Services (NC & SLB) with images that contain the latest updates for Server 2016 for now and are going to test again. Hoping that any of the recent updates will also fix the SLB cert issues.

Thanks
Robert

**Comment by AnirbanPaul** [comment]
[+Saaransh]

Hi Robert
Let us know if you are facing the same issue after re-deployment.

If you can give us access to the setup, we should be able to resolve more quickly.

Thanks
Anirban

**Comment by rhochmayr** [comment]
Hi Anirban

After testing the process to update the certificates on a newly deployed NC service I still ran into issues after the change has been completed. 

The NC service itself seems to be running fine though as far as I can tell. The issue now is that the Hyper-V hosts report "PolicyConfigurationFailure" (Failed to configure the policies on the host device.).

I did the certificate change on the NC nodes in following sequence:

1. Request new cert and imported to NC nodes with private key
2. Set-NetworkControllerCluster -CredentialEncryptionCertificate <newCertObject>
3. Verified HV and NC Node Status => OK
4. Set-NetworkController -ServerCertificate <newCertObject>
5. Verified HV and NC Node Status => OK
6. Updated SSL bindings on remaining nodes via netsh http command
7. Verified HV and NC Node Status => OK
8. Rebooted NC Nodes after each other
9. Verified HV and NC Node Status => OK
10. Rebooted NC Nodes after each other
11. Removed old cert from NC Nodes
12. Verified HV and NC Node Status => OK
13. Rebooted NC Nodes after each other
14. Verified HV and NC Node Status => FAILED 

After the last NC Node has been restarted I started to recieve the Warnings on the HV Hosts from above.

The NC Service itself is beeing reported as Ready and OK when checking the SF ServiceTypes.

netstat -anp tcp |findstr 6640 on the Hosts now show:
LISTENING
FIN_WAIT_2
ESTABLISHED

I'm more than happy to provide you or one of your collegues with access to the system if that is an option. How would we arrange this? I can send you my email address if that helps.

Thanks
Robert

**Comment by AnirbanPaul** [comment]
Please provide access to the system. You can send to anpaul@microsoft.com<mailto:anpaul@microsoft.com>

Sent from my iPhone

On Dec 6, 2017, at 4:05 PM, rhochmayr <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Anirban

After testing the process to update the certificates on a newly deployed NC service I still ran into issues after the change has been completed.

The NC service itself seems to be running fine though as far as I can tell. The issue now is that the Hyper-V hosts report "PolicyConfigurationFailure" (Failed to configure the policies on the host device.).

I did the certificate change on the NC nodes in following sequence:

  1.  Request new cert and imported to NC nodes with private key
  2.  Set-NetworkControllerCluster -CredentialEncryptionCertificate
  3.  Verified HV and NC Node Status => OK
  4.  Set-NetworkController -ServerCertificate
  5.  Verified HV and NC Node Status => OK
  6.  Updated SSL bindings on remaining nodes via netsh http command
  7.  Verified HV and NC Node Status => OK
  8.  Rebooted NC Nodes after each other
  9.  Verified HV and NC Node Status => OK
  10. Rebooted NC Nodes after each other
  11. Removed old cert from NC Nodes
  12. Verified HV and NC Node Status => OK
  13. Rebooted NC Nodes after each other
  14. Verified HV and NC Node Status => FAILED

After the last NC Node has been restarted I started to recieve the Warnings on the HV Hosts from above.

The NC Service itself is beeing reported as Ready and OK when checking the SF ServiceTypes.

netstat -anp tcp |findstr 6640 on the Hosts now show:
LISTENING
FIN_WAIT_2
ESTABLISHED

I'm more than happy to provide you or one of your collegues with access to the system if that is an option. How would we arrange this? I can send you my email address if that helps.

Thanks
Robert

**Comment by rhochmayr** [comment]
Hi Anirban

Adding the new Credential resource as you mentioned resolved the communication issue between the NC Nodes and the HV Hosts.

I added / updated the Credential Object with following commands:

```
$cred=New-Object Microsoft.Windows.Networkcontroller.credentialproperties
$cred.type="X509Certificate"
$cred.username=""
$cred.value="<New ThumbPrint>"
$cred

New-NetworkControllerCredential -ConnectionUri "<ConnectionUri>" -Properties $cred -ResourceId "<ResourceId from NCCred Object with old ThumbPrint>"

```
This actually updated the existing Credential Object and the Value now shows the new ThumbPrint

Afterwards I restart the NCHostAgent services on all Hyper-V Hosts and checked connectivitiy with following commands:

```
Invoke-Command -ComputerName (get-clusternode -Cluster "<Hyper-V Cluster Name>").name -ScriptBlock {Restart-Service NCHostAgent -Force}
Invoke-Command -ComputerName (get-clusternode -Cluster "<Hyper-V Cluster Name>").name -ScriptBlock {netstat -anp tcp |findstr 6640}
```

Now the Hosts showed 1 listening and 3 established sessions again.

Checking the NC Configuration State on the Hyper-V Hosts with following command also completed without any errors. 

```
$credential = Get-Credential -UserName "<domain\username>" -Message "Enter NC Admin Credentials"
Debug-NetworkControllerConfigurationState -NetworkController "<NC Rest Endpoint>" -Credential $credential
```

VMs using Network Virtualization regained connectivity as well, so all is good at this stage.

Just to recap, the necessary steps for us to successfully replace a NC certificate (issued by internal CA) is now following:

1. Import Cert with private key on all NC nodes
2. Run Set-NetworkControllerCluster -CredentialEncryptionCertificate \<CertObect\>
3. Run Set-NetworkController -ServerCertificate \<CertObect\> on one of the nodes
4. Update SSL bindings on remaining nodes via netsh http command
5. Run Get-NetworkControllerServer -ConnectionUri \<NC REST uri\> | ConvertTo-Json -Depth 10
5a. In the output of this, you will see a Credential resource with type as X509Certificate.
5b. Query this credential resource by executing Get-NetworkControllerCredential -ConnectionUri \<NC REST uri\> -ResourceID \<Resource ID of the cred\> | ConvertTo-Json -Depth 10
5c. Check if the cert specified in this cred resource matches with the new NC Server cert. In our case the old thumbprint was still showing up here.
6. Run New-NetworkControllerCredential -ConnectionUri \<ConnectionUri\> -Properties $cred -ResourceId \<ResourceId from NCCred Object with old ThumbPrint\>
7. Restart NCHostAgents on Hyper-V Hosts

Many thanks for your help
Robert
