### ISSUE TITLE
Port Profile Data on NC VM was set incorrectly to 2

### ISSUE THREAD

**Issue by JMesser81** [Microsoft/SDN#15]
NC ports were blocked incorrectly (or wrong port settings) due to profile data being set to 2 on NIC. To change, I had to do the following and then restart NC VMs and NC Host Agent

$vmNics = Get-VMNetworkAdapter -VMName "NC-01"

(Get-VMSwitchExtensionPortFeature -FeatureId 9940cd46-8b06-43bb-b9d5-93d50381fd56 -VMNetworkAdapter $vmNics[0]).SettingData

$currentProfile = Get-VMSwitchExtensionPortFeature -FeatureId 9940cd46-8b06-43bb-b9d5-93d50381fd56 -VMNetworkAdapter $vmNics[0]

$currentProfile.SettingData.ProfileData = 1

Set-VMSwitchExtensionPortFeature -VMSwitchExtensionFeature $currentProfile -VMNetworkAdapter $vmNics[0]

**Comment by RamanDhillon** [comment]
Looks like ConfigureHostNetworking>EnableVFP function is force setting all the NICs to PPData = 2. It needs to be removed as all the NICs are already being configured with their corresponding PPIDs and PPData in SetPortAndProfile function.

**Comment by JMesser81** [comment]
This was fixed as a result of TP5 code merge
