### ISSUE TITLE
WinCNI not setting default DNS suffix for Windows pods in 1709

### ISSUE THREAD

**Issue by PatrickLang** [Microsoft/SDN#150]
When I create pods in Windows Server version 1709 based cluster, I can't get DNS resolution to work with shortnames. For example I have a service exposed called `db` below, but I can't resolve it without expanding the FQDN. This is because the Connection-specific DNS Suffix isn't set in the pod/container

```none
Ethernet adapter vEthernet (71e9952fd2588121a7e5ec3b14f7382161f0fd3128d1c923a726932f327df003_l2bridge):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #3
   Physical Address. . . . . . . . . : 00-15-5D-0C-CC-06
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::8cdd:d393:1384:e4c8%24(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.244.3.149(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.240.0.1
   DNS Servers . . . . . . . . . . . : 10.0.0.10
   NetBIOS over Tcpip. . . . . . . . : Disabled

C:\inetpub\wwwroot>nslookup db
Server:  kube-dns.kube-system.svc.cluster.local
Address:  10.0.0.10

*** kube-dns.kube-system.svc.cluster.local can't find db: Non-existent domain

C:\inetpub\wwwroot>nslookup db.ff.svc.cluster.local
Server:  kube-dns.kube-system.svc.cluster.local
Address:  10.0.0.10

Name:    db.ff.svc.cluster.local
Address:  10.0.246.133
```

**Comment by funky81** [comment]
Hi @patrick have you solved the problem?

**Comment by PatrickLang** [comment]
no, it's still active. @JMesser81 do you know current status?

**Comment by JMesser81** [comment]
Unfortunately we have not made these changes in wincni.exe. We are pivoting towards using the CNI plugins (currently in PR review) available on https://github.com/containernetworking/plugins (changed are in forked branch - https://github.com/rakelkar/plugins in the windowsCni branch).

**Comment by JMesser81** [comment]
These *new* Windows CNI plugins (named win-l2bridge and win-overlay) are still a work in progress but this is where our development (and bug fixes) are being focused.

**Comment by JMesser81** [comment]
We went ahead and updated wincni.exe binary found in this repo Microsoft/SDN/Kubernetes/cni/wincni.exe. This should resolve the DNS problem
