### ISSUE TITLE
generate.py dependent on python2 - not available in latest ubuntu

### ISSUE THREAD

**Issue by gpkmajeti** [Microsoft/SDN#159]
following folder doesn't exist in Ubuntu - #!/usr/bin/python2 

**Solution:**
https://github.com/Microsoft/SDN/blob/master/Kubernetes/linux/manifest/generate.py need to be made python3 compatible

(or)

**Either the documentation needs to be changed at following location to install**
https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/creating-a-linux-master
To install python 2.7 and the py file should be changed to use "#!/usr/bin/python2.7"

**Comment by gkudra-msft** [comment]
Confirmed on Ubuntu 17.10.1. Gone are the days in which Python 2 was included on every Linux system, apparently... Thanks for the catch! Installing it is better than relying on Python 3 existing, so I will open PRs shortly.
