### ISSUE TITLE
Removing SDN causes existing virtual machines to become unreachable

### ISSUE THREAD

**Issue by Bearcomtech** [Microsoft/SDN#164]
Hi,

Due to a lot of problems with SDN I have tried to remove and unregister the SDN service from vmm to later reinstall. However, this is very problematic. After following this guide https://docs.microsoft.com/en-us/system-center/vmm/sdn-remove?view=sc-vmm-1711 I come to the point of removing network controller. When I “remove network controller” and the service goes away it all looks fine in VMM but the Virtual machines that uses same logical switch (for vlan communication) that NC controller were connected to have now lost all connectivity.

When removing the SDN the virtual switches on the hosts gets updated with a disable of the extension “Microsoft Azure VFP Switch Extension” This is all fine since the NC is no longer in place. However, all virtual machines connected to this switch through VMM has a tag on its network adapters. This tag is “MandatoryFeatureName” with parameter “{Ethernet Switch Port VFP Settings}”
This makes the current adapter unusable on the switch. If I disconnect the adapter from the network in vmm and reconnect it, vmm will put this tag back on the vm netadapter. It seems like it does not understand that the network service is gone.

My question now is how do I make VMM update my virtual machines adapters to not use that parameter when SDN is uninstalled?

**Comment by devalian** [comment]
Hi, 

same here for me. have 3 environment going through SDN removal process due to certain limitation, and/or problem of others. 

VM lost connectivity, i basically created a powershell script just to remove vNIC and add a new one, with cloned mac and inject ip into VM.

**Comment by micros01** [comment]
May I ask what kind of problems and limitations you are facing?

**Comment by devalian** [comment]
As this thread from bearcomtech, I shall not jump the gun too much. Briefly,

1) cluster 1 : Sdn lost connectivity. Corrupted beyond repair, unable to remove either. So we rebuild 
2) cluster 2 : would like to use nested virtualization. After enable Sdn, vlan based network nested virtualization also doesn't work. Hence we remove the sdn, but go thru above. 
3) cluster 3 : vmms hung, vm stopping, rhs deadlock. Just to remove Sdn to isolate issue. But I don't think is Sdn related, just Sdn is there make it difficult to bring online our vm after failure cause NC might be dead from the failure. 

Anyhow, current focus is removal Sdn causes network connectivity lost.

**Comment by Bearcomtech** [comment]
To not remove the network adapter my current solution would be to set the vm adapters in "not connected" state via vmm scripting to later outside on the hosts connect them back. When VMM sets the adpters in "not connected" vmm remove the mandatoryfeaturename tag. After this one can connect back with for example failoverclusternamanger. However the danger i see is that vmm might re add this tag on an update of the virtual machine which would cause trouble. that is why i want vmm to "understand" that nc service is no longer used.

**Comment by blake-thompson** [comment]
We have had most of these problems while uninstalling SDN. Think we have done it 5 times so far. The main issue seems to be caused by the Host not un-registering the MUX agent and if you look in hyperv switch management extension it normally is still connected to the microsoft azure VFP switch extension. AS sdn is no longer there to control this all the network cards no longer work. If we unselect this then the networking works. We sometimes get an issue still on some network cards created under SDN. These we have to remove or powershell a replacement in.
