### ISSUE TITLE
Placement failed for Service Deployment

### ISSUE THREAD

**Issue by khsoong** [Microsoft/SDN#167]
What could have caused this error during VMMSDNExpress setup?

**Comment by grcusanz** [comment]
There can be a number of reasons why placement could fail... VM is marked as highly available, but no highly available storage or cluster available, not enough disk space, not enough memory, logical networks not associated with the host's network sites.  Check the job history to see if there is more information.  You can also try to deploy the service template from the Admin console and it will give you the reason for the placement decision.

**Comment by khsoong** [comment]
Thanks Greg.
1. VM is marked as highly available, but no highly available storage or cluster available - Not for my case.
2. Not enough disk space, not enough memory - Possible, will check. Thanks !
3.  logical networks not associated with the host's network sites - Not sure what you mean. Do you have example, please?
