### ISSUE TITLE
Error in Northbound Interface documentation?

### ISSUE THREAD

**Issue by J0F3** [Microsoft/SDN#172]
Hi,

I have a short question about the 'credentials' resource of the Network Controller. 
The documentation states that for the type 'x509Certificate' the value is the Subject Name of the certificate.

> X509Certificate: this element represents the certificate subject name
https://msdn.microsoft.com/en-us/library/mt766865.aspx

But when I look at the SDN Express Script it sets the value to the Thumbprint of the certificate. Which actually makes quite more sense. But the question is now which one is really correct? Is the documentation wrong or is there an error in the SDN Express Script?

Thx,
Jonas

**Comment by grcusanz** [comment]
Hi Jonas, the documentation is incorrect.  It should be the thumbprint since there could be multiple certificates with the same subject name, while the thumbprint is most likely unique.  I've notified the content owners and you should see it updated in the near future.  Thanks!

**Comment by J0F3** [comment]
Hi Greg,
Cool, thank you for your response and the clarification. 👍
