### ISSUE TITLE
SDN Software Load Balancer - Not advertising BGP routes

### ISSUE THREAD

**Issue by rhochmayr** [Microsoft/SDN#174]
Hi there

after deploying network controllers and software load balancers via VMM service templates we are at a stage where the BGP sessions against our peering partners have been established successfully. 

Howevers, no routes are beeing advertised by the SLB MUXes to the peers. The only relevant traffic I can see during a capture are BGP keep alives.

Also the Hyper-V Hosts are still showing following warning:

> Source:     SoftwareLoadBalancerManager
> Code:        HostNotConnectedToController
> Message:   Host is not Connected.

SoftwareLoadBalancer-HostPlugin Eventlogs on the Hyper-V Hosts also show:

> Failure while connecting to SLBM: socket_error: WSAConnect error code = 10060

I assume this is because the SLB Manager VIP is not beeing advertised by the SLBs yet and therefore not routable/accessable from the management network(s).

I also tried creating a tenant vNET and enabling NAT, but the assigned IP address from the Public VIP Pool is also not beeing advertised by the Load Balancers.

I checked the configs by running DumpSlbRestState and Debug-NetworkController and all seems good on first sight. The diagnostics-slbstateResults.Json includes MuxRoutes with the SLB Manager VIP for each MUX.

At what point should the LoadBalancers start advertising routes for assigned VIP addresses, including the SLB Manager VIP? 

Thanks
Robert

**Comment by grcusanz** [comment]
Hi Robert, which version of windows are you using... Windows Server 2016 or Windows Server Version 1709?  Assuming Windows Server 2016, I would look closer at the BGP messages.  You should see a handshake take place before the keepalives start and the SLBM VIP should be advertised.  Restarting the slbmux service will cause this handshake and advertisement to be reestablished.  Let me know what you see in the messages.

**Comment by rhochmayr** [comment]
Hi Greg

Thanks, yes, we are running Windows Server 2016 (1607) Core on all Hosts and SDN VMs. 

Just ran a trace while restarting the SlbMux services and I can now see the BGP Update Messages are being sent shortly after the service comes up on the load balancers. 

The update messages include routes for the SLB Manager VIP and a Public VIP address from the test tenant vNet. So I would say it's all working as expected on the SDN side so far and I will check with our networking guys on how things are looking at their end.

Thanks a lot for the quick help on this one!

Cheers
Robert

**Comment by Wawszczak** [comment]
Dear All,

I have the same issue. I have restarted MUXes several times, but I can see in the trace only INIT messages (BGP ID 1) from both sides and after that Keep Alive messages (BGP ID 4).
Could somebody help with that?

Best Regards,
Stanislaw
