### ISSUE TITLE
SLB Load Balancer doesn't work with Linux VMs

### ISSUE THREAD

**Issue by lflint** [Microsoft/SDN#190]
We're able to create SDN Load Balancers to load-balance inbound TCP port 80 between two Windows VMs, running Failover Cluster with a VIP. However, when we try the same thing with CentOS, RedHat, or BSD-based VMs, there's no response.

Working example:
- Windows 2016
- Failover Cluster
- 2 nodes, 10.0.0.5 & 10.0.0.6
- 1 VIP 10.0.0.10/255.255.255.255
- TCP port 80 (IIS)
- Probe port 59999
- Floating IP

Non-working example:
- RedHat/CentOS 7.3
- PCS Cluster
- 2 nodes, 10.0.0.5 & 10.0.0.6
- 1 VIP 10.0.0.10/255.255.255.255
- TCP port 80 (Apache)
- Probe port 59999
- Floating IP

Can see probe port 80 & 59999 traffic reaching the Linux VMs using tcpdump, but no response is sent from the Linux VMs. Traffic does work from non-VIP IP addresses.

The same issues are experienced when we use a BSD-based OPNSense cluster.

Public IP address NAT works fine with the Linux VMs, just not private addresses.

**Comment by grcusanz** [comment]
This was due to a bug in the SDN load balancer that was fixed earlier this year.  If your NC, hosts and muxes are fully patched then Linux DIPs should now work properly.
