### ISSUE TITLE
Overlay Kubernetes - Adapter was not found

### ISSUE THREAD

**Issue by funky81** [microsoft/SDN#194]
Hi @JMesser81, I checkout your latest PR for overlay. And I've got following messages.
- CIDR = 10.168.0.0/16
- Windows Host Machine (node) = 192.168.91.2/24
- Linux Host Machine (master) = 192.168.91.200/24

How to solve it?

> PS C:\k> flanneld.exe --kubeconfig-file=C:\k\config --iface=192.168.91.2 --ip-masq=1 --kube-subnet-mgr=1
I0310 03:30:45.123146    6288 main.go:422] Searching for interface using 192.168.91.2
I0310 03:30:45.246152    6288 main.go:499] Using interface with name vEthernet (Ethernet) and address 192.168.91.2
I0310 03:30:45.246152    6288 main.go:516] Defaulting external address to interface address (192.168.91.2)
I0310 03:30:45.254147    6288 kube.go:131] Waiting 10m0s for node controller to sync
I0310 03:30:45.254147    6288 kube.go:294] Starting kube subnet manager
I0310 03:30:46.254246    6288 kube.go:138] Node controller sync successful
I0310 03:30:46.254246    6288 main.go:240] Created subnet manager: Kubernetes Subnet Manager - nw2
I0310 03:30:46.255243    6288 main.go:243] Installing signal handlers
I0310 03:30:46.266161    6288 main.go:358] Found network config - Backend type: vxlan
I0310 03:30:46.276200    6288 vxlan_windows.go:113] VXLAN config: {name:vxlan0 macPrefix:0E-2A VNI:4096 Port:4789 GBP:false DirectRouting:false}
I0310 03:30:46.307168    6288 vxlan_windows.go:183] Attempting to create HNS network, request: {"Name":"vxlan0","Subnets":[{"AddressPrefix":"10.168.0.0/16","GatewayAddress":"10.168.0.1","Policies":[{"Type":"VSID","VSID":4096}]}],"Type":"Overlay"}
**E0310 03:30:46.376188    6288 main.go:285] Error registering network: unable to create network [vxlan0], error: HNS failed with error : An adapter was not found.**
I0310 03:30:46.377171    6288 main.go:338] Stopping shutdownHandler...

I do found few bugs on your start.ps1
- Flanneld value for iface parameter should be Windows Host Machine public IP. cmiiw
- I've put `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12` to bypass error code caused by https protocol

**Comment by funky81** [comment]
It turns out I have to turn off Windows Firewall using this command `NetSh Advfirewall set allprofiles state off` then I modify the [start.ps1](https://github.com/funky81/SDN/blob/flannel/Kubernetes/flannel/overlay/start.ps1)

but somehow kube-flannel for windows node, still in init and dont move.
Any solutions?

**Comment by armahan** [comment]
Hi, I have got an error message about the network creating.

PS C:\k> C:\flannel\flanneld.exe --kubeconfig-file=C:\k\config --iface=10.101.0.157 --ip-masq=1 --kube-subnet-mgr=1
I0409 10:11:58.321251    2584 main.go:422] Searching for interface using 10.101.0.157
I0409 10:11:58.381263    2584 main.go:499] Using interface with name Ethernet and address 10.101.0.157
I0409 10:11:58.381263    2584 main.go:516] Defaulting external address to interface address (10.101.0.157)
E0409 10:11:58.392288    2584 main.go:237] Failed to create SubnetManager: failed to read net conf: open /etc/kube-flannel/net-conf.json: The system cannot find the path specified.

**Comment by kinglionsoft** [comment]
Failed when creating netword on Windows Server 2019 which is hosted by VMWare.
```bash
flanneld.exe --kubeconfig-file=C:\k\config --iface=192.168.0.248 --ip-masq=1 --kube-subnet-mgr=1

flanneld.exe : I1112 16:50:31.237948    5408 main.go:422] Searching for interface using 192.168.0.248
所在位置 行:1 字符: 1
+ flanneld.exe --kubeconfig-file=C:\k\config --iface=192.168.0.248 --ip ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (I1112 16:50:31....g 192.168.0.248:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
2018-11-12 16:50:31.379841 I | Interfaces : [{0  5000 false  0 0 }]
I1112 16:50:31.495253    5408 main.go:206] Could not find valid interface matching 192.168.0.248: error looking up interface 192.168.0.248: no index found for interface ""
E1112 16:50:31.495253    5408 main.go:230] Failed to find interface to use that matches the interfaces and/or regexes provided
```

**Comment by daschott** [comment]
We will update the overlay instructions and remove assumptions from the corresponding scripts soon. First of all, we are working on improving Flannel in host-gw mode on Windows this month. You can already use Flannel in host-gw mode today following these instructions: https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/getting-started-kubernetes-windows

**Comment by daschott** [comment]
sorry for the long delay here... The new overlay instructions are out now. We have made a number of improvements since last year such that Windows Server version 1809 or above are supported on Kubernetes v1.14 or above. 

More information on how to troubleshoot Kubernetes networking can be found here:
https://techcommunity.microsoft.com/t5/Networking-Blog/Troubleshooting-Kubernetes-Networking-on-Windows-Part-1/ba-p/508648

Here is the K8s docs: https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-nodes/

Please submit new issue and cc me if you continue seeing problems on latest supported versions, thank you!
