### ISSUE TITLE
SDN Role didn't installed on VMs

### ISSUE THREAD

**Issue by EngASaaid** [Microsoft/SDN#201]
**i faced this error during deploying NC service template** 

Error (22042)
The service NCFABRIC was not successfully deployed. Review the event log to determine the cause and corrective actions.

Recommended Action
The deployment can be restarted by retrying the job.

Error (22753)
The script command with properties: Type (PreInstall), Deployment Order (3) and Parent Type (ApplicationProfile), failed to complete successfully. Refer to the errors list for more information.

Recommended Action
If the script command's job restart action is set to restart, then the script will be re-executed.  Otherwise, the script command will be skipped when the job is restarted, in which case corrective action should be taken to mitigate the effects of the script command failure.

Error (22631)
The script command exit code 2148734208 matched the failure policy setting "Match any value other than zero." Standard output log data: "icrosoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlS
                     et\Services\Tcpip6\Parameters\
PSParentPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlS
                     et\Services\Tcpip6
PSChildName        : Parameters
PSDrive            : HKLM
PSProvider         : Microsoft.PowerShell.Core\Registry

Windows IP Configuration

Registration of the DNS resource records for all adapters of this computer has been initiated. Any errors will be reported in the Event Viewer in 15 minutes.
[2018-03-22T12:31:02.2140973-07:00]Installing NetworkController Role..
[2018-03-22T12:31:03.5384059-07:00]Caught an exception:
[2018-03-22T12:31:03.5540220-07:00]    Exception Type: System.Exception
[2018-03-22T12:31:03.5696575-07:00]    Exception Message: ArgumentNotValid: The role, role service, or feature name is not valid: 'NetworkController'. The name was not found.
[2018-03-22T12:31:03.5696575-07:00]    Excepti"

Recommended Action
If the script command's job restart action is set to restart, then the script will be re-executed. Otherwise, the script command will be skipped when the job is restarted, in which case corrective action should be taken to mitigate the effects of the script command failure.

Error (22753)
The script command with properties: Type (PreInstall), Deployment Order (3) and Parent Type (ApplicationProfile), failed to complete successfully. Refer to the errors list for more information.

Recommended Action
If the script command's job restart action is set to restart, then the script will be re-executed.  Otherwise, the script command will be skipped when the job is restarted, in which case corrective action should be taken to mitigate the effects of the script command failure.

Error (22631)
The script command exit code 2148734208 matched the failure policy setting "Match any value other than zero." Standard output log data: "icrosoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlS
                     et\Services\Tcpip6\Parameters\
PSParentPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlS
                     et\Services\Tcpip6
PSChildName        : Parameters
PSDrive            : HKLM
PSProvider         : Microsoft.PowerShell.Core\Registry

Windows IP Configuration

Registration of the DNS resource records for all adapters of this computer has been initiated. Any errors will be reported in the Event Viewer in 15 minutes.
[2018-03-22T12:31:04.0069203-07:00]Installing NetworkController Role..
[2018-03-22T12:31:05.3193927-07:00]Caught an exception:
[2018-03-22T12:31:05.3350191-07:00]    Exception Type: System.Exception
[2018-03-22T12:31:05.3350191-07:00]    Exception Message: ArgumentNotValid: The role, role service, or feature name is not valid: 'NetworkController'. The name was not found.
[2018-03-22T12:31:05.3350191-07:00]    Excepti"

Recommended Action
If the script command's job restart action is set to restart, then the script will be re-executed. Otherwise, the script command will be skipped when the job is restarted, in which case corrective action should be taken to mitigate the effects of the script command failure.

Error (22753)
The script command with properties: Type (PreInstall), Deployment Order (3) and Parent Type (ApplicationProfile), failed to complete successfully. Refer to the errors list for more information.

Recommended Action
If the script command's job restart action is set to restart, then the script will be re-executed.  Otherwise, the script command will be skipped when the job is restarted, in which case corrective action should be taken to mitigate the effects of the script command failure.

Error (22631)
The script command exit code 2148734208 matched the failure policy setting "Match any value other than zero." Standard output log data: "icrosoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlS
                     et\Services\Tcpip6\Parameters\
PSParentPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlS
                     et\Services\Tcpip6
PSChildName        : Parameters
PSDrive            : HKLM
PSProvider         : Microsoft.PowerShell.Core\Registry

Windows IP Configuration

Registration of the DNS resource records for all adapters of this computer has been initiated. Any errors will be reported in the Event Viewer in 15 minutes.
[2018-03-22T12:31:08.0188675-07:00]Installing NetworkController Role..
[2018-03-22T12:31:10.2544197-07:00]Caught an exception:
[2018-03-22T12:31:10.2700457-07:00]    Exception Type: System.Exception
[2018-03-22T12:31:10.2700457-07:00]    Exception Message: ArgumentNotValid: The role, role service, or feature name is not valid: 'NetworkController'. The name was not found.
[2018-03-22T12:31:10.2700457-07:00]    Excepti"

Recommended Action
If the script command's job restart action is set to restart, then the script will be re-executed. Otherwise, the script command will be skipped when the job is restarted, in which case corrective action should be taken to mitigate the effects of the script command failure.

Error (20400)
3 parallel subtasks failed during execution.

Error (21952)
Application deployment failed for one or more tiers or application hosts in the service NCFABRIC. Check job logs to get more information on the failed operation.

Recommended Action
Check error messages and retry the operation if needed.

**Comment by grcusanz** [comment]
The network controller role is only available in the Datacenter edition of Windows Server.   Make sure you are not using Standard.
