### ISSUE TITLE
DIP vs CA

### ISSUE THREAD

**Issue by khsoong** [Microsoft/SDN#202]
Dynamic IP address (DIP) in the context of SLB vs Customer Address (CA) in the context of VXLAN.
Are these 2 addresses the same?

**Comment by grcusanz** [comment]
Sorry about the slow response on this.  DIPs refer to the back-end connections for SLB and are mapped to specific IPconfiguration objects on the network interface.  So in the case of the DIP being connected to a virtual subnet the yes, it is the same as the CA.
