### ISSUE TITLE
Cannot Set Gateway Capacity (Mbps) in Network Controller Manager Role - SDN V2

### ISSUE THREAD

**Issue by doulakis** [Microsoft/SDN#211]
Hey Guys,

We need to increase the Gateway Capacity (Mbps) from 1000 to 40000 in Network Controller Manager Role through VMM or PowerShell and we get the below error:

_**Network service threw an unhandled exception: ' ' (Error ID: 50125)
Work with the network service vendor to fix the problem.**_

Please Find the powershell script here:
```
$runAsAccount = Get-SCRunAsAccount -ID "b48458b0-e1cd-48b4-97c7-25f8cfee9727"
# Get Configuration Provider 'Microsoft Network Controller'
$configurationProvider = Get-SCConfigurationProvider -Name "Microsoft Network Controller"
$networkService = Get-SCNetworkService -ID "4b4b88f3-6eba-4953-b5a5-e7227fd21d1f"
Set-SCNetworkService -NetworkService $networkService -Name "Network Controller" -Description "" -ConnectionString "serverurl=https://networkcontroller.mydomain.com;servicename=NC" -RunAsAccount $runAsAccount
# Get Fabric role 'config'
$fabricRole = Get-SCFabricRole -ID "ae41efdb-de4d-471c-9fb9-190bd08bf673"

# Get Fabric role 'Default'
$fabricRole = Get-SCFabricRole -ID "5fe10d49-cae9-4285-afd4-4e8f6d6ebb87"
# Get Virtual Switch Extension Manager 'Network Controller'
$networkController = Get-SCVirtualSwitchExtensionManager -ID "f90c2c5f-33c6-41ca-b0d7-d647c5417a79"
# Get Allocated IP Address 'xxx.xxx.xxx.xxx'
$publicIPV4Address = Get-SCIPAddress -ID "b1af9201-be84-4795-980f-ff9caa5bc147"
$publicIPAddresses = @()
$publicIPAddresses += $publicIPV4Address
$subnetVlansGreVip = @()
$subnetVlanGreVipIPv4 = New-SCSubnetVLan -Subnet "192.168.1.0/24" -VLanID "0"
$subnetVlansGreVip += $subnetVlanGreVipIPv4
$fabricRoleConfiguration = New-SCGatewayRoleConfiguration -GatewayCapacityKbps 40960000 -PublicIPAddresses $publicIPV4Address -RedundantResourceCount 0 -GreVipSubnets $subnetVlansGreVip
$fabricRole = Set-SCFabricRole -FabricRole $fabricRole -GatewayConfiguration $fabricRoleConfiguration
$serviceFabricRoleResource = $fabricRole.Services | where { $_.ID -eq "01b9e678-65cb-46cf-8cc8-c5321494f2ac" }
```
The VMM Version is 1801 (4.1.3223.0)

**Comment by doulakis** [comment]
@grcusanz @JMesser81 Could you please take a look? It is a blocker for us, we cannot go into production because of this problem.

**Comment by rhochmayr** [comment]
Hi Doulakis

The Gateway Capacity cannot be changed for pools with connected/configured gateways from what I have seen. For VMM this means removing the GW Nodes from the NC Service and re-adding them with the required capacity. 

Not sure if this is intended behavior by MS, but at least is being returned in the response.

Network service threw an unhandled exception: '{
  "error": {
    "code": "InternalServerError",
    "message": "The value for \"GatewayPool.GatewayCapacityKiloBitsPerSecond\" parameter cannot be changed while one or more gateways are configured.",
    "target": "Default",
    "innerError": "Message: The value for \"GatewayPool.GatewayCapacityKiloBitsPerSecond\" parameter cannot be changed while one or more gateways are configured., Target: Default, InnerException: null, 

Hope that helps.

Cheers,
Robert

**Comment by grcusanz** [comment]
Robert is correct, the gateway capacity can't be changed while there are gateways in it.   The only option is to remove the gateway nodes and re-add them after adjusting the capacity.

**Comment by rizamg** [comment]
Any guidance on how to do this when the SDN is integrated with VMM? Would something like this with Powershell work?

$uri = "https://networkcontroller"
$gateways = Get-NetworkControllerGateway -ConnectionUri $uri
$gwPool = Get-NetworkControllerGatewayPool -ConnectionUri $uri

$gwPool.Properties.GatewayCapacityKiloBitsPerSecond = 20000000

$gateways | ForEach {Remove-NetworkControllerGateway $_}
New-NetworkControllerGatewayPool -ConnectionUri $uri -ResourceId $gwPool.ResourceId -Properties $gwPool.Properties
$gateways | ForEach {New-NetworkControllerGateway -ConnectionUri $uri -ResourceId $_.ResourceId -Properties $_.Properties}

Then I would assume just refresh the network service?
