### ISSUE TITLE
[network issue]windows pod in kubernetes cluster is unable to access to internet

### ISSUE THREAD

**Issue by Cherishty** [microsoft/SDN#227]
Hi team, following the guide in 
https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/getting-started-kubernetes-windows#cluster-subnet-def
and
https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/creating-a-linux-master
I can create a kubernetes cluster with a master node and windows worker node.

Env:
Linux Master Node : ubuntu 16.04
Windows Worker Node: winserver 1709
kubernetes version: 1.9.1

However, when I setting up a pod in this windows worker I find it can not access to internet, something I have done is listed in below:

**1.** In Master Node I check kube-dns and it is RUNNING

**2.** In Windows Node I ran:
c:\k\kubectl.exe  --kubeconfig=c:\k\config get nodes -o=custom-columns=Name:.status.nodeInfo.operatingSystem,PO
DCidr:.spec.podCIDR --no-headers
linux     10.244.0.0/24
windows   10.244.1.0/24

**3.** Inside the Windows Pod I ran:
#below scripts ran in windows pod, based on cni+hostGW
**3.1**
PS C:\app> ipconfig
Windows IP Configuration
Ethernet adapter vEthernet (06b7336c2c000b344e4784c08dfb2743137e63f445d69e460894b858ad3aad6c_l2bridge):

   Connection-specific DNS Suffix  . : default.svc.cluster.local
   Link-local IPv6 Address . . . . . : fe80::f5c4:1671:7a33:b49e%24
   IPv4 Address. . . . . . . . . . . : 10.244.1.253
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.244.1.2

**3.2**
PS C:\app> ping www.google.com
Ping request could not find host www.google.com. Please check the name and try again.

**3.3**
#10.190.176.110 is the master node ip
PS C:\app> ping 10.190.176.110

Pinging 10.190.176.110 with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 10.190.176.110:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

**3.4**
#10.190.178.50 is the windows node ip
PS C:\app> ping 10.190.178.50

Pinging 10.190.178.50 with 32 bytes of data:
Reply from 10.190.178.50: bytes=32 time<1ms TTL=128
Reply from 10.190.178.50: bytes=32 time<1ms TTL=128
Reply from 10.190.178.50: bytes=32 time<1ms TTL=128
Reply from 10.190.178.50: bytes=32 time<1ms TTL=128

Ping statistics for 10.190.178.50:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

**3.5**
#10.244.1.2 is the windows node, podCIDR ip
PS C:\app> ping 10.244.1.2

Pinging 10.244.1.2 with 32 bytes of data:
Reply from 10.244.1.2: bytes=32 time=7ms TTL=128
Reply from 10.244.1.2: bytes=32 time<1ms TTL=128
Reply from 10.244.1.2: bytes=32 time<1ms TTL=128
Reply from 10.244.1.2: bytes=32 time<1ms TTL=128

Ping statistics for 10.244.1.2:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 7ms, Average = 1ms

below is the log of kube-proxy:
`parameter. For a list of approved verbs, type Get-Verb.
W0702 02:58:59.514206    1964 server.go:185] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
I0702 02:58:59.536208    1964 server_windows.go:99] Using Kernelspace Proxier.
W0702 02:58:59.564215    1964 proxier.go:465] clusterCIDR not specified, unable to distinguish between internal and external traffic
I0702 02:58:59.572211    1964 proxier.go:481] Hns Network loaded with info = &{l2bridge 8e68213e-9443-4395-a50c-3977cb7bdba7}
I0702 02:58:59.572211    1964 proxier.go:501] minSyncPeriod: 0s, syncPeriod: 30s, burstSyncs: 2
I0702 02:58:59.572211    1964 server.go:426] Version: v1.9.1
I0702 02:58:59.573230    1964 server.go:443] setting OOM scores is unsupported in this build
W0702 02:58:59.573230    1964 server.go:450] Failed to start in resource-only container "/kube-proxy": resource-only containers unsupported in this platform
I0702 02:58:59.573230    1964 healthcheck.go:309] Starting goroutine for healthz on 0.0.0.0:10256
I0702 02:58:59.574206    1964 bounded_frequency_runner.go:170] sync-runner Loop running
I0702 02:58:59.574206    1964 config.go:102] Starting endpoints config controller
I0702 02:58:59.601206    1964 controller_utils.go:1019] Waiting for caches to sync for endpoints config controller
I0702 02:58:59.574206    1964 config.go:202] Starting service config controller
I0702 02:58:59.574206    1964 reflector.go:202] Starting reflector *core.Endpoints (15m0s) from k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85
I0702 02:58:59.575207    1964 reflector.go:202] Starting reflector *core.Service (15m0s) from k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85
I0702 02:58:59.601206    1964 controller_utils.go:1019] Waiting for caches to sync for service config controller
I0702 02:58:59.602210    1964 reflector.go:240] Listing and watching *core.Endpoints from k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85
I0702 02:58:59.602210    1964 reflector.go:240] Listing and watching *core.Service from k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85
I0702 02:58:59.605211    1964 config.go:124] Calling handler.OnEndpointsAdd
I0702 02:58:59.606213    1964 config.go:224] Calling handler.OnServiceAdd
I0702 02:58:59.606213    1964 proxier.go:897] Setting endpoints for "kube-system/kubernetes-dashboard:" to [0xc042036140]
I0702 02:58:59.606213    1964 config.go:124] Calling handler.OnEndpointsAdd
I0702 02:58:59.606213    1964 proxier.go:897] Setting endpoints for "kube-system/kube-dns:dns" to []
I0702 02:58:59.606213    1964 config.go:224] Calling handler.OnServiceAdd
I0702 02:58:59.607209    1964 proxier.go:897] Setting endpoints for "kube-system/kube-dns:dns-tcp" to []
I0702 02:58:59.608206    1964 config.go:224] Calling handler.OnServiceAdd
I0702 02:58:59.608206    1964 config.go:124] Calling handler.OnEndpointsAdd
I0702 02:58:59.608206    1964 proxier.go:897] Setting endpoints for "kube-system/heapster:" to [0xc0429fc080]
I0702 02:58:59.608206    1964 config.go:224] Calling handler.OnServiceAdd
I0702 02:58:59.608206    1964 config.go:224] Calling handler.OnServiceAdd
I0702 02:58:59.608206    1964 config.go:224] Calling handler.OnServiceAdd
I0702 02:58:59.608206    1964 config.go:124] Calling handler.OnEndpointsAdd
I0702 02:58:59.609208    1964 config.go:124] Calling handler.OnEndpointsAdd
I0702 02:58:59.609208    1964 proxier.go:897] Setting endpoints for "default/win-webserver:" to [0xc042036340]
I0702 02:58:59.609208    1964 config.go:124] Calling handler.OnEndpointsAdd
I0702 02:58:59.609208    1964 proxier.go:897] Setting endpoints for "default/kubernetes:https" to [0xc0420363c0]
I0702 02:58:59.609208    1964 config.go:124] Calling handler.OnEndpointsAdd
I0702 02:58:59.609208    1964 config.go:124] Calling handler.OnEndpointsAdd
I0702 02:58:59.701209    1964 shared_informer.go:122] caches populated
I0702 02:58:59.701209    1964 controller_utils.go:1026] Caches are synced for endpoints config controller
I0702 02:58:59.706208    1964 config.go:110] Calling handler.OnEndpointsSynced()
I0702 02:58:59.702210    1964 shared_informer.go:122] caches populated
I0702 02:58:59.706208    1964 proxier.go:938] Not syncing hns until Services and Endpoints have been received from master
I0702 02:58:59.707209    1964 controller_utils.go:1026] Caches are synced for service config controller
I0702 02:58:59.710210    1964 config.go:210] Calling handler.OnServiceSynced()
I0702 02:58:59.708209    1964 proxier.go:934] syncProxyRules took 2.0009ms
I0702 02:58:59.712210    1964 proxier.go:296] Adding new service port "default/kubernetes:https" at 11.0.0.1:443/TCP
I0702 02:58:59.714208    1964 proxier.go:296] Adding new service port "kube-system/kubernetes-dashboard:" at 11.0.4.111:80/TCP
I0702 02:58:59.720151    1964 proxier.go:296] Adding new service port "kube-system/kube-dns:dns" at 11.0.0.10:53/UDP
I0702 02:58:59.721226    1964 proxier.go:296] Adding new service port "kube-system/kube-dns:dns-tcp" at 11.0.0.10:53/TCP
I0702 02:58:59.722223    1964 proxier.go:296] Adding new service port "kube-system/heapster:" at 11.0.213.227:80/TCP
I0702 02:58:59.723219    1964 proxier.go:296] Adding new service port "default/hello-kube:" at 11.0.134.7:80/TCP
I0702 02:58:59.724219    1964 proxier.go:296] Adding new service port "default/win-webserver:" at 11.0.110.180:80/TCP
I0702 02:58:59.726210    1964 proxier.go:957] Syncing Policies
I0702 02:58:59.727223    1964 proxier.go:967] ====Applying Policy for default/kubernetes:https====
I0702 02:58:59.761220    1964 proxier.go:119] Hns Endpoint resource, {"ID":"b799ce1e-da48-480d-b2eb-c13436cf5653","Name":"Ethernet","VirtualNetwork":"8e68213e-9443-4395-a50c-3977cb7bdba7","VirtualNetworkName":"l2bridge","Policies":[{"Type":"L2Driver"}],"MacAddress":"00:11:22:33:44:55","IPAddress":"10.190.178.37","IsRemoteEndpoint":true}
I0702 02:58:59.762210    1964 proxier.go:113] Endpoint resource found, (*winkernel.endpointsInfo)(0xc0420363c0)({
 ip: (string) (len=13) "10.190.178.37",
 port: (uint16) 443,
 isLocal: (bool) false,
 macAddress: (string) (len=17) "00:11:22:33:44:55",
 hnsID: (string) (len=36) "b799ce1e-da48-480d-b2eb-c13436cf5653",
 refCount: (uint16) 1
})
I0702 02:58:59.767212    1964 proxier.go:1017] Associated endpoints [([]hcsshim.HNSEndpoint) (len=1 cap=1) {
 (hcsshim.HNSEndpoint) {
  Id: (string) (len=36) "b799ce1e-da48-480d-b2eb-c13436cf5653",
  Name: (string) (len=8) "Ethernet",
  VirtualNetwork: (string) (len=36) "8e68213e-9443-4395-a50c-3977cb7bdba7",
  VirtualNetworkName: (string) (len=8) "l2bridge",
  Policies: ([]json.RawMessage) (len=1 cap=4) {
   (json.RawMessage) (len=23 cap=32) {
    00000000  7b 20 22 54 79 70 65 22  20 3a 20 22 4c 32 44 72  |{ "Type" : "L2Dr|
    00000010  69 76 65 72 22 20 7d                              |iver" }|
   }
  },
  MacAddress: (string) (len=17) "00:11:22:33:44:55",
  IPAddress: (net.IP) (len=16 cap=16) 10.190.178.37,
  DNSSuffix: (string) "",
  DNSServerList: (string) "",
  GatewayAddress: (string) "",
  EnableInternalDNS: (bool) false,
  DisableICC: (bool) false,
  PrefixLength: (uint8) 0,
  IsRemoteEndpoint: (bool) true
 }
}
] for service [default/kubernetes:https]
I0702 02:58:59.769210    1964 proxier.go:1029] Trying to Apply Policies for service (*winkernel.serviceInfo)(0xc0429ce000)({
 clusterIP: (net.IP) (len=16 cap=16) 11.0.0.1,
 port: (int) 443,
 protocol: (core.Protocol) (len=3) "TCP",
 nodePort: (int) 0,
 targetPort: (int) 443,
 loadBalancerStatus: (core.LoadBalancerStatus) {
  Ingress: ([]core.LoadBalancerIngress) {
  }
 },
 sessionAffinityType: (core.ServiceAffinity) (len=8) "ClientIP",
 stickyMaxAgeSeconds: (int) 10800,
 externalIPs: ([]*winkernel.externalIPInfo) <nil>,
 loadBalancerIngressIPs: ([]*winkernel.loadBalancerIngressInfo) <nil>,
 loadBalancerSourceRanges: ([]string) {
 },
 onlyNodeLocalEndpoints: (bool) false,
 healthCheckNodePort: (int) 0,
 hnsID: (string) "",
 nodePorthnsID: (string) "",
 policyApplied: (bool) false
})
I0702 02:58:59.786209    1964 proxier.go:119] Hns loadbalancer policy resource, {"ID":"6dbd64ee-070d-42a6-aea0-85392e760241","References":["/endpoints/b799ce1e-da48-480d-b2eb-c13436cf5653"],"Policies":[{"ExternalPort":443,"InternalPort":443,"Protocol":6,"Type":"ELB","VIPs":["11.0.0.1"]}]}
I0702 02:58:59.786209    1964 proxier.go:1046] Hns LoadBalancer resource created for cluster ip resources 11.0.0.1, Id [6dbd64ee-070d-42a6-aea0-85392e760241]
I0702 02:58:59.788209    1964 proxier.go:113] +++Policy Successfully applied for service +++, (*winkernel.serviceInfo)(0xc0429ce000)({
 clusterIP: (net.IP) (len=16 cap=16) 11.0.0.1,
 port: (int) 443,
 protocol: (core.Protocol) (len=3) "TCP",
 nodePort: (int) 0,
 targetPort: (int) 443,
 loadBalancerStatus: (core.LoadBalancerStatus) {
  Ingress: ([]core.LoadBalancerIngress) {
  }
 },
 sessionAffinityType: (core.ServiceAffinity) (len=8) "ClientIP",
 stickyMaxAgeSeconds: (int) 10800,
 externalIPs: ([]*winkernel.externalIPInfo) <nil>,
 loadBalancerIngressIPs: ([]*winkernel.loadBalancerIngressInfo) <nil>,
 loadBalancerSourceRanges: ([]string) {
 },
 onlyNodeLocalEndpoints: (bool) false,
 healthCheckNodePort: (int) 0,
 hnsID: (string) (len=36) "6dbd64ee-070d-42a6-aea0-85392e760241",
 nodePorthnsID: (string) "",
 policyApplied: (bool) true
})
I0702 02:58:59.789209    1964 proxier.go:967] ====Applying Policy for kube-system/kubernetes-dashboard:====
I0702 02:58:59.821214    1964 proxier.go:119] Hns Endpoint resource, {"ID":"6f0a6774-3823-46ff-ad3f-3b48930f8232","Name":"Ethernet","VirtualNetwork":"8e68213e-9443-4395-a50c-3977cb7bdba7","VirtualNetworkName":"l2bridge","Policies":[{"Type":"L2Driver"}],"MacAddress":"00:11:22:33:44:55","IPAddress":"10.244.0.2","IsRemoteEndpoint":true}
I0702 02:58:59.821214    1964 proxier.go:113] Endpoint resource found, (*winkernel.endpointsInfo)(0xc042036140)({
 ip: (string) (len=10) "10.244.0.2",
 port: (uint16) 9090,
 isLocal: (bool) false,
 macAddress: (string) (len=17) "00:11:22:33:44:55",
 hnsID: (string) (len=36) "6f0a6774-3823-46ff-ad3f-3b48930f8232",
 refCount: (uint16) 1
})
I0702 02:58:59.872211    1964 proxier.go:1017] Associated endpoints [([]hcsshim.HNSEndpoint) (len=1 cap=1) {
 (hcsshim.HNSEndpoint) {
  Id: (string) (len=36) "6f0a6774-3823-46ff-ad3f-3b48930f8232",
  Name: (string) (len=8) "Ethernet",
  VirtualNetwork: (string) (len=36) "8e68213e-9443-4395-a50c-3977cb7bdba7",
  VirtualNetworkName: (string) (len=8) "l2bridge",
  Policies: ([]json.RawMessage) (len=1 cap=4) {
   (json.RawMessage) (len=23 cap=32) {
    00000000  7b 20 22 54 79 70 65 22  20 3a 20 22 4c 32 44 72  |{ "Type" : "L2Dr|
    00000010  69 76 65 72 22 20 7d                              |iver" }|
   }
  },
  MacAddress: (string) (len=17) "00:11:22:33:44:55",
  IPAddress: (net.IP) (len=16 cap=16) 10.244.0.2,
  DNSSuffix: (string) "",
  DNSServerList: (string) "",
  GatewayAddress: (string) "",
  EnableInternalDNS: (bool) false,
  DisableICC: (bool) false,
  PrefixLength: (uint8) 0,
  IsRemoteEndpoint: (bool) true
 }
}
] for service [kube-system/kubernetes-dashboard:]
I0702 02:58:59.873218    1964 proxier.go:1029] Trying to Apply Policies for service (*winkernel.serviceInfo)(0xc0429f8000)({
 clusterIP: (net.IP) (len=16 cap=16) 11.0.4.111,
 port: (int) 80,
 protocol: (core.Protocol) (len=3) "TCP",
 nodePort: (int) 30292,
 targetPort: (int) 9090,
 loadBalancerStatus: (core.LoadBalancerStatus) {
  Ingress: ([]core.LoadBalancerIngress) {
  }
 },
 sessionAffinityType: (core.ServiceAffinity) (len=4) "None",
 stickyMaxAgeSeconds: (int) 10800,
 externalIPs: ([]*winkernel.externalIPInfo) <nil>,
 loadBalancerIngressIPs: ([]*winkernel.loadBalancerIngressInfo) <nil>,
 loadBalancerSourceRanges: ([]string) {
 },
 onlyNodeLocalEndpoints: (bool) false,
 healthCheckNodePort: (int) 0,
 hnsID: (string) "",
 nodePorthnsID: (string) "",
 policyApplied: (bool) false
})
I0702 02:58:59.893210    1964 proxier.go:119] Hns loadbalancer policy resource, {"ID":"dfc42bc5-9493-4ca9-9a4f-bb89ca84ca23","References":["/endpoints/6f0a6774-3823-46ff-ad3f-3b48930f8232"],"Policies":[{"ExternalPort":80,"InternalPort":9090,"Protocol":6,"Type":"ELB","VIPs":["11.0.4.111"]}]}
I0702 02:58:59.893210    1964 proxier.go:1046] Hns LoadBalancer resource created for cluster ip resources 11.0.4.111, Id [dfc42bc5-9493-4ca9-9a4f-bb89ca84ca23]
I0702 02:58:59.911211    1964 proxier.go:119] Hns loadbalancer policy resource, {"ID":"c970ddb7-6757-49c7-a914-859ea5e42a82","References":["/endpoints/6f0a6774-3823-46ff-ad3f-3b48930f8232"],"Policies":[{"ExternalPort":30292,"InternalPort":9090,"Protocol":6,"Type":"ELB"}]}
I0702 02:58:59.911211    1964 proxier.go:1064] Hns LoadBalancer resource created for nodePort resources 11.0.4.111, Id [c970ddb7-6757-49c7-a914-859ea5e42a82]
I0702 02:58:59.913215    1964 proxier.go:113] +++Policy Successfully applied for service +++, (*winkernel.serviceInfo)(0xc0429f8000)({
 clusterIP: (net.IP) (len=16 cap=16) 11.0.4.111,
 port: (int) 80,
 protocol: (core.Protocol) (len=3) "TCP",
 nodePort: (int) 30292,
 targetPort: (int) 9090,
 loadBalancerStatus: (core.LoadBalancerStatus) {
  Ingress: ([]core.LoadBalancerIngress) {
  }
 },
 sessionAffinityType: (core.ServiceAffinity) (len=4) "None",
 stickyMaxAgeSeconds: (int) 10800,
 externalIPs: ([]*winkernel.externalIPInfo) <nil>,
 loadBalancerIngressIPs: ([]*winkernel.loadBalancerIngressInfo) <nil>,
 loadBalancerSourceRanges: ([]string) {
 },
 onlyNodeLocalEndpoints: (bool) false,
 healthCheckNodePort: (int) 0,
 hnsID: (string) (len=36) "dfc42bc5-9493-4ca9-9a4f-bb89ca84ca23",
 nodePorthnsID: (string) (len=36) "c970ddb7-6757-49c7-a914-859ea5e42a82",
 policyApplied: (bool) true
})
I0702 02:58:59.918208    1964 proxier.go:967] ====Applying Policy for kube-system/kube-dns:dns====
I0702 02:58:59.919220    1964 proxier.go:1017] Associated endpoints [([]hcsshim.HNSEndpoint) <nil>
] for service [kube-system/kube-dns:dns]
E0702 02:58:59.920211    1964 proxier.go:1025] Endpoint information not available for service kube-system/kube-dns:dns. Not applying any policy
I0702 02:58:59.922272    1964 proxier.go:967] ====Applying Policy for kube-system/kube-dns:dns-tcp====
I0702 02:58:59.923211    1964 proxier.go:1017] Associated endpoints [([]hcsshim.HNSEndpoint) <nil>
] for service [kube-system/kube-dns:dns-tcp]
E0702 02:58:59.933211    1964 proxier.go:1025] Endpoint information not available for service kube-system/kube-dns:dns-tcp. Not applying any policy
I0702 02:58:59.934211    1964 proxier.go:967] ====Applying Policy for kube-system/heapster:====
I0702 02:58:59.968221    1964 proxier.go:119] Hns Endpoint resource, {"ID":"36500581-8053-4448-b2aa-cdd6647049a3","Name":"Ethernet","VirtualNetwork":"8e68213e-9443-4395-a50c-3977cb7bdba7","VirtualNetworkName":"l2bridge","Policies":[{"Type":"L2Driver"}],"MacAddress":"00:11:22:33:44:55","IPAddress":"10.244.0.5","IsRemoteEndpoint":true}
I0702 02:58:59.968221    1964 proxier.go:113] Endpoint resource found, (*winkernel.endpointsInfo)(0xc0429fc080)({
 ip: (string) (len=10) "10.244.0.5",
 port: (uint16) 8082,
 isLocal: (bool) false,
 macAddress: (string) (len=17) "00:11:22:33:44:55",`

For my side , I think it may result in a wrong configuration of **cni** or **kube-proxy**, actually for the file located in https://github.com/Microsoft/SDN/blob/master/Kubernetes/windows/cni/config/l2bridge.conf
I am not sure how to set **dns.Nameservers** and the **EndpointPolicy** of route. And from log of kube-proxy  seems it does not support to give special parameter anymore ? 

Quite appreciate for your help!

**Comment by Cherishty** [comment]
Finally, all the issue is fixed according to https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/common-problems#my-windows-pods-cannot-ping-external-resources

please kindly close this issue. Thanks!

**Comment by gudipudipradeep** [comment]
Run the following command in container  so i can able to connect the internet.
netsh interface ip add dns name="vEthernet (5864216160f5c1f8111806c535a4_vxlan0)" 10.98.0.10 index=1

**Comment by daschott** [comment]
@gudipudipradeep Thank you for reporting this issue. Can you describe your environment with a bit more detail? Also this issue is to track kubernetes cluster is unable to reach internet. Your issue sounds like you cannot reach internal network. Can you please open a new issue and include following details:
* Windows version and KBs applied (`Get-Hotfix`)
* Kubernetes version
* Environment (on-prem, AWS VM, Azure VMs, etc?)
* Network solution used
* Docs that were used to deploy Kubernetes

Feel free to CC me and we will follow up with you & take a look. Thanks!
