### ISSUE TITLE
Management and HNV Provider logical networks limited to non-zero VLANs

### ISSUE THREAD

**Issue by JMesser81** [Microsoft/SDN#24]
You workaround the “VLAN 0” issue by forcing the function to run every time, which will go and put the port profile in all cases.
In the SDNExpress.ps1 script, there is a configuration script  Script "SetPortAndProfile_$($VMInfo.VMName)_$($nic.Name)", under this, you need to put a return $false in TestScript portion which returns $false without performing the checks it was doing before
 
Script "SetPortAndProfile_$($VMInfo.VMName)_$($nic.Name)"  
TestScript = {
return $false #This is the change: TestScript return $False Instead of $True

Those checks found that VLAN 0 matches the VLAN tag on Management NIC and returned $true earlier which caused the SetScript to skip. Now with TestScript returning $false, the SetScript executes.
This is temporary fix (workaround), final solution will come from dev(s).

**Comment by nwoodmsft** [comment]
This should be fixed in the latest commit (updated to SDNExpress for Server 2016 RTM)
