### ISSUE TITLE
Post VFP Switch Deployment - Network Controller loses IP connectivity due to AllowUntaggedTraffic set to $false

### ISSUE THREAD

**Issue by uday31in** [Microsoft/SDN#25]
PS C:\Windows\system32> Get-VMNetworkAdapterIsolation -VMName NC-01 | select *

IsolationMode        : None
AllowUntaggedTraffic : False
DefaultIsolationID   : 0
MultiTenantStack     : Off
ParentAdapter        : VMNetworkAdapter (Name = 'Management', VMName = 'NC-01') [VMId = 'de4ba4c9-61e1-4fb7-ab32-f3770827cae7']
IsTemplate           : True
CimSession           : CimSession: .
ComputerName         : CONTOSOHV01
IsDeleted            : False

**Comment by JMesser81** [comment]
This has been fixed
