### ISSUE TITLE
Flannel pod issue - Windows node connecting to Linux Master

### ISSUE THREAD

**Issue by mgroux520** [microsoft/SDN#255]
Hi folks,

Have run into this issue following the latest documentation I could find -   https://github.com/Microsoft/SDN/tree/master/Kubernetes/flannel/l2bridge

...which is a scaled down version of this:  https://1drv.ms/w/s!AgH65RVQdrbiglNr7P7P4VrO8Rxr (that I could not get to).  So someone pointed me to this copy of it:  https://statemigration.com/validation-guide-rs5-kubernetes-on-windows-using-flannel/

Everything seems to go fine:  I create my Master Linux node with kubeadm, get a Linux worker node to join just fine.  But adding a Windows node has been troublesome.  I am running 1-11-2 across the board.

Docker Version on Windows Node:

C:\k>docker version
Client:
 Version:      17.06.2-ee-16
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   9ef4f0a
 Built:        Thu Jul 26 16:43:19 2018
 OS/Arch:      windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-16
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   9ef4f0a
  Built:        Thu Jul 26 16:52:17 2018
  OS/Arch:      windows/amd64
  Experimental: false

kubectl version from Master:
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

The current status:  
- Per the instructions I linked above, you should be able to use the './start.ps1' script to get the node joined and start the appropriate kubelet/proxy services.  This does show/exhibit when I do a 'kubectl get nodes' from the Master:
NAME                               STATUS    ROLES     AGE       VERSION
ec2amaz-4ipanbr                    Ready     <none>    17m       v1.11.2
ip-10-74-19-159.xxx.xxxxxxx.com   Ready     <none>    5d        v1.11.2
ip-10-74-19-196.xxx.xxxxxxx.com   Ready     master    6d        v1.11.2
((((Note, I changed some of the info above for security purposes))))

- All nodes are Ready.  All pods are Running fine, including dns, flannel, etcd, etc on master and linux worker - EXCEPT for the Windows node flannel pod, i.e. :
kube-system   kube-flannel-ds-cppg6       0/1       Init:ImagePullBackOff   0          19m

- When I do a Describe on this pod, I see the following:
Normal   Pulling     17m (x2 over 18m)   kubelet, ec2amaz-4iponrr  pulling image "quay.io/coreos/flannel:v0.10.0-amd64"
  Warning  Failed      17m (x2 over 17m)   kubelet, ec2amaz-4iponrr  Error: ErrImagePull
  Warning  Failed      17m                 kubelet, ec2amaz-4iponrr  Failed to pull image "quay.io/coreos/flannel:v0.10.0-amd64": rpc error: code = Unknown desc = failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer \\?\C:\ProgramData\docker\windowsfilter\0e9b8be7f76c784181efebc271cf08f98d4b7bc8aa4ae64420b8c1d53f98181f: The system cannot find the path specified.
  Normal   BackOff     3m (x268 over 17m)  kubelet, ec2amaz-4iponrr  Back-off pulling image "quay.io/coreos/flannel:v0.10.0-amd64"

- It seemed like a Docker issue coming from the Windows node, so I tried to manually download the file there, and this is what I get:
C:\k\cni\config>docker pull quay.io/coreos/flannel:v0.10.0-amd64
v0.10.0-amd64: Pulling from coreos/flannel
ff3a5c916c92: Extracting [==================================================>]  2.066MB/2.066MB
8a8433d1d437: Download complete
306dc0ee491a: Download complete
856cbd0b7b9c: Download complete
af6d1e4decc6: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer \\?\C:\ProgramData\docker\windowsfilter\ff01c82e666741dedcd84e7637df6c376d831652dfbfeed773ad7f2652bede9c: The system cannot find the path specified.

- Basically it repeats the error.  I am behind a proxy, but have successfully downloaded/updated as necessary.  One of the things I believe may be causing the issue is the " \\?\C:\Prog .... " if front of the path for the file, but for the life of me I cannot figure out where that is coming from, nor how to correct it.  I have duplicated this twice now with 2 different instances on AWS.

- I went as far as to get into the Docker image, but as far as I can tell everything looks ok.  But I am by no means an expert with Docker or the manipulation of images.  Have tried to determine if Docker needed some special proxy settings, but could find none that were specific to Windows 2016 **Core**.  
- There may be some other factor I am not taking into account, like when I do a 'kubectl version' from the Windows node I get a connection error from the server.  But not sure if that is a factor here with this config or not.

Anyone have any insight ?  Can provide other info as necessary....

**Comment by mutazn** [comment]
I think Flannel DaemonSet is scheduled to only target Linux nodes by applying this [node-selector](https://github.com/Microsoft/SDN/blob/master/Kubernetes/flannel/l2bridge/manifests/node-selector-patch.yml).

**Comment by juangps96** [comment]
Same issue, Do you have some update?

**Comment by daschott** [comment]
Thanks, Mutazn suggestion is right.
