### ISSUE TITLE
The certificate provided for client authentication cannot be found on the node

### ISSUE THREAD

**Issue by uday31in** [Microsoft/SDN#26]
VERBOSE: [NC-01]: LCM:  [ End    Set      ]  [[Script]CreateControllerCluster]  in 71.9900 seconds.
VERBOSE: Exception: PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functio
nality with error message: The certificate provided for client authentication cannot be found on the node NC-
01.CONTOSO.COM. Ensure that the certificate exists and try again 
VERBOSE: Disabling tracing for NC.
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApp
ly,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfi
guration'.
VERBOSE: An LCM method call arrived from computer CONTOSODC with user sid S-1-5-21-82120362-3978326868-922153
898-500.
VERBOSE: [NC-01]: LCM:  [ Start  Set      ]
VERBOSE: [NC-01]: LCM:  [ Start  Resource ]  [[Script]StopNCTracing]
VERBOSE: [NC-01]: LCM:  [ Start  Test     ]  [[Script]StopNCTracing]
VERBOSE: [NC-01]: LCM:  [ End    Test     ]  [[Script]StopNCTracing]  in 0.0470 seconds.
VERBOSE: [NC-01]: LCM:  [ Start  Set      ]  [[Script]StopNCTracing]
VERBOSE: [NC-01]:                            [[Script]StopNCTracing] Performing the operation "Set-TargetReso
urce" on target "Executing the SetScript with the user supplied credential".
VERBOSE: [NC-01]: LCM:  [ End    Set      ]  [[Script]StopNCTracing]  in 5.1060 seconds.
VERBOSE: [NC-01]: LCM:  [ End    Resource ]  [[Script]StopNCTracing]
VERBOSE: [NC-01]: LCM:  [ End    Set      ]
VERBOSE: [NC-01]: LCM:  [ End    Set      ]    in  5.8570 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 5.933 seconds
PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error 
message: The certificate provided for client authentication cannot be found on the node NC-01.CONTOSO.COM. 
Ensure that the certificate exists and try again 
At C:\SDN\SDNExpress\scripts\SDNExpress.ps1:2656 char:9
+         Start-DscConfiguration -Path .\ConfigureNetworkControllerClus ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : NC-01

**Comment by nwoodmsft** [comment]
This has been root caused to an issue with NC cert locations which cause the Install-NetworkControllerCluster cmdlet to fail to find the NC cert in the LocalMachine\My certificate store.

There is a case during InstallRootCerts where in some environments the script may find a pre-existing node cert in the certificate store (e.g. CN=NC-01.mydomain.com) and it will then skip the installation of the pfx on that node. This later causes Install-NetworkControllerCluster to fail when it can not locate the expected cert.

We were able to verify in Uday's case that forcing the pfx installation to always occur on the NC node resolved this issue. We will do some further verification of this fix and then update GitHub TP5/Master branches. 

Thanks.
