### ISSUE TITLE
Request - 2VM NICs support for SLB muxes

### ISSUE THREAD

**Issue by wind06106** [Microsoft/SDN#27]
I would like to request to support that 2VM NICs (attached to the PA logical network and transit network)  when deploying SLB muxes.

**Comment by manishmsft** [comment]
thanks for your input. we will discuss this and get back to you.

**Comment by nwoodmsft** [comment]
Good news - this change (to enable multiple NICs within MUX or other infra VMs) has already been made to the main SDNExpress scripts in my fork. I will be creating a PR for this today.

**Comment by nwoodmsft** [comment]
Please see the latest SDNExpress scripts within the Master branch: https://github.com/Microsoft/SDN/tree/master/SDNExpress

You can now add additional NICs to the SLB MUXes by simply editing the FabricConfig.psd1 and adding a second NIC to the MUX VM's NIC array. For example, this would connect the MUX to both the HNVPA and the Management logical networks:

`
              @{    
                VMName="MUX-01"
		VMMemory=4GB
                NICs=@(
                @{
                        Name="HNVPA"
                        IPAddress="10.10.56.2"
                        LogicalNetwork = "HNVPA"
                        MacAddress="00-1D-C8-00-01-02"
                        PortProfileID="00000000-0000-0000-0000-000000000000"
                        PortProfileData=2
                    },
                    @{
                        Name="Management"
                        IPAddress="10.11.108.8"
                        LogicalNetwork = "Management"
                        MacAddress="00-1D-C8-00-04-01"
                        PortProfileID="00000000-0000-0000-0000-000000000000"
                        PortProfileData=1
                    }
                )
              }
`
