### ISSUE TITLE
Policy creation failed: HNS failed with error : An expected policy was not found.

### ISSUE THREAD

**Issue by lanoxx** [microsoft/SDN#273]
I am trying to get Flannel running on Windows 1803 using the overlay mode (e.g. vxlan). I am getting the following error from kube-proxy:

> Policy creation failed: HNS failed with error : An expected policy was not found.

This error is printed repeatedly every few seconds amidst other output, which makes is really hard to see what is going on.

**Comment by daschott** [comment]
overlay mode requires Windows Server, version 1809 with KB4489899 (or higher).
