### ISSUE TITLE
Sandbox error trying to setup overlay mode with flannel

### ISSUE THREAD

**Issue by lanoxx** [microsoft/SDN#274]
I am trying to setup Kubernetes with Flannel in Overlay mode and I am getting the following error:

> Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-flannel-ds-amd64-h6p5c": Error response from daemon: network host not found

The output is being repeated every second which makes it hard to see what is going on.

**Comment by jekstrom** [comment]
I am also getting this error on the kube-proxy pod. Running the [win-webserver pod from the guide](https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/deploying-resources) starts fine.

I also see `Endpoint information not available for service` repeated in the kube-proxy error logs for every service, but I think that is a symptom.

@lanoxx were you able to resolve this issue?

**Comment by lanoxx** [comment]
No, I switched to ovn-kubernetes which worked much better.

**Comment by daschott** [comment]
This means the kube-flannel Linux pod was attempted to be scheduled on Windows. Please apply the NodeSelector so that the Flannel DaemonSet targets Linux only so the erroneous scheduling to Windows nodes does not occur.
