### ISSUE TITLE
l2bridge creation fails with error: The device is not ready.

### ISSUE THREAD

**Issue by antymon4o** [microsoft/SDN#277]
Hello Everyone!
I am trying to configure and use docker containers connected to a tenant virtual network. 
Using the guide from https://github.com/Microsoft/SDN/tree/master/Containers everything works fine up until the last step (Create an l2bridge Container Network). The error I get from docker create network is:

**Error response from daemon: hnsCall failed in Win32: The device is not ready. (0x15)**

The result from _docker network ls_ shows only "_nat_" and "_none_", even thou there is a new virtual switch created with the Azure VPF extension enabled.  
In the event viewer on channel Microsoft-Windows-Host-Network-Service-Admin there are these events after the create command:
 - Event 1 (Information):
HNS-Network-Create :- 
 Network id = '{b2ab65c9-1b0a-4e3c-9412-52b7ce527864}'.
 Network type = 'LAYERED'.
  Result code = '0x0'.
 - Event 2 (Error):
HNS-Network-Create :- 
 Network id = '{711c6220-6024-4cec-ac84-9bf72e173295}'.
 Network type = 'L2BRIDGE'.
  Result code = '0x80070015'. 

The tenant virtual machine has Windows Server 2019 Datacenter Edition with docker version 18.09.0.

Can anyone help with what could be the reason for this error? Or what other things to look for and check?

**Comment by antymon4o** [comment]
Hi, again! I have more info on the issue. 

During _docker network create_ command I enabled traces. In the etl log there were _Error_ events from provider _Microsoft.Windows.HostNetworkingService.PrivateCloudPlugin_.

This is the sequence:

> message="WinHttpSendRequest failed" error="-2,147,012,867"
> message="WinHttpSendRequest failed" error="-2,147,012,867"
> message="Private cloud plugin is not yet bootstraped" error="-2,147,024,875"

The error code from the last message is actually 80070015 in HEX. I believe this corresponds to the error message in Microsoft-Windows-Host-Network-Service-Admin event log from my previous writing. So probably the device is not ready error is because of the private cloud plugin not yet bootstraped. Now, the question is why is it not bootstrapped? And what needs to be done in order for the plugin to get bootstrapped?

One more thing that I guess is connected to the bootstrapping. In the etl there is an event Initialize from the same provider with following info: 

> path="machine/plugins?comp=nmagent&amp;type=getinterfaceinfov1" addr="169.254.169.254" format="xml" port="80"

Unfortunately, this address and port is not accessible from the tenant virtual machine. Is there any configuration that I am missing?

Any idea or suggestion will be helpful!
Thank you in advance!

**Comment by petkodeivn** [comment]
We have the same issue in our test environment. Did someone manage to deploy this on-premises?

**Comment by MicahMcKittrick-MSFT** [comment]
@dcuomo @madhanrm @ksubrmnn  would any of you be able to assist on this? Or add someone who might?

**Comment by JMesser81** [comment]
Sorry for the slow response. It appears as though you're trying to create a local l2bridge network running on an Azure IaaS VM to connect container endpoints to the Azure VNet, is that correct? Are you using Windows Server 2019?

You shouldn't need to use those instructions or run the scripts listed anymore as we have removed support for private cloud plugin.

**Comment by antymon4o** [comment]
I have deployed SDN on premises on Windows Server 2019. The tenant VM is also Windows Server 2019. What is the way to run docker containers connected to VNet?

**Comment by antymon4o** [comment]
@JMesser81 , I tried the docker network create on a tenant VM with Windows Server 2016 and with Windows Server 1803 and the behavior is the same - HNS failed with error, Result code = '0x80070015'.
Can you tell what is the supported way to run containers in VNet?

**Comment by daschott** [comment]
@antymon4o thanks for your patience. Can you clarify whether you are trying to attach to Azure vNet or is this on prem? Your goal is to attach containers to a vnet, right?

If on azure, can you use azure-CNI: https://docs.microsoft.com/en-us/azure/virtual-network/deploy-container-networking#deploy-plug-in-for-docker-containers 

If on-prem and you want to use l2bridge there is a win-bridge plugin that you can also use in a similar way: https://github.com/Microsoft/SDN/blob/master/Kubernetes/flannel/l2bridge/cni/win-bridge.exe 

We are working on docs to outline this process for l2bridge docker containers in coming months. Perhaps an easier way to get started today on-prem is to use a transparent network. Containers should behave like a VM in many regards. For example, to create network:
```
docker network create -d transparent --subnet <subnet> --gateway <gateway> -o com.docker.network.windowsshim.interface=<interface name> my_transparent
``` 

To launch a container:
```
docker run -d --rm --network my_transparent --ip <someIP> --dns <dns server> mcr.microsoft.com/windows/servercore:1809 ping -t localhost
```

**Comment by daschott** [comment]
There is a blog on l2bridge that was recently published, can you try the steps outlined there? 
https://techcommunity.microsoft.com/t5/networking-blog/l2bridge-container-networking/ba-p/1180923

**Comment by ksubrmnn** [comment]
@JocelynBerrendonner
