### ISSUE TITLE
Misleading procedure

### ISSUE THREAD

**Issue by AlexisLessard** [Microsoft/SDN#29]
I followed this [procedure[](url)](https://technet.microsoft.com/en-us/library/mt729074%28v=sc.16%29.aspx?f=255&MSPPError=-2147217396)  from technet trying to install the templates of the network controller deployment and there was an issue with my logical switch. It is written in this other [procedure[](url)](https://technet.microsoft.com/en-us/library/mt732315(v=sc.16).aspx) that teaming is not supported for NC deployment. My switchs didn't onboarded. I am going to try to redo the procedure with a new switch. Also, you can insert the product key in the open designer after you imported the template. Useful trick to not have to go inside the console. We are really excited to working with this technology. Tell me if you want feedback or ideas for test!

**Comment by AlexisLessard** [comment]
I tried again with VSwich without any extensions or teaming and it worked. My switch seemed to have onboarded. However, the software load balancer didn't start and I couldn't ping between my virtual machines on virtual networks. I have 2 host, one of wich was hosting a network controller. Does TP5 support VM's on the same host as the NC?

**Comment by RamanDhillon** [comment]
Hi Alexis. Thanks for trying it out and reaching out with your queries. 
Regarding the product Key, yes, that is being addressed in future releases. And yes, a host can have Network Controller as well other VMs (SLB MUXes, Gateway VMs, Tenant Workload VMs).
To take a look at your issues, could you provide your email where we could reach and discuss further?

**Comment by AlexisLessard** [comment]
Thank you for your answer! My email is: alexis.lessard@dti.ulaval.ca.
