### ISSUE TITLE
Flannel assigns same ip for containers

### ISSUE THREAD

**Issue by guhuajun** [Microsoft/SDN#301]
Greetings,

I am researching Kubernetes on Windows with Flannel + VxLan based the files from this repo.
Containers can be scheduled to Windows node, but cannot be assigned a unique IP.

helper.psm1 was modified to make sure flanneld could be run in the foreground. So, I can check the output, but it looks like that nothing goes wrong.
Analytic and Operation log are enabled via Windows Admin Center, but I cannot find something useful.

Any hint for debugging this issue will be appreciated.

**Environment**
- VirtualBox 5.2.22 (3 VMs with Bridged network, promiscuous mode are enabled.)
- CentOS 7.4.1708 + Windows Server Insider (10.0.18298.1000)

**Screenshots**
![image](https://user-images.githubusercontent.com/14121694/51017929-ba90f400-15b0-11e9-8799-ec67c0ed57b7.png)
![image](https://user-images.githubusercontent.com/14121694/51018068-3e4ae080-15b1-11e9-8db5-45ad4930419e.png)
![image](https://user-images.githubusercontent.com/14121694/51018248-e06ac880-15b1-11e9-88c8-580eacfc3bcf.png)

**Comment by guhuajun** [comment]
@ksubrmnn Thanks for your contribution to flannel 0.11.

I have tried with Windows Server Insider 10.0.18317.1000 + flannel 0.11 + vxlan. But the issue still occurs. So is this configuration still under developing?

![image](https://user-images.githubusercontent.com/14121694/52165486-7b336e80-273c-11e9-87b4-d8acbf267bd8.png)

**Comment by ksubrmnn** [comment]
There is still an update to the SDN starter scripts. It will be out today.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ksubrmnn** [comment]
Hi @guhuajun,
Please try https://github.com/Microsoft/SDN/pull/311

**Comment by guhuajun** [comment]
@ksubrmnn Thanks a lot! Let me have a try.

**Comment by guhuajun** [comment]
@ksubrmnn I can confirm the duplicate ip issue was resolved by #311. A Windows Container Web Server can be opened in web browser.  Next I will try the network connectivity between a Linux container and a Windows container.

![image](https://user-images.githubusercontent.com/14121694/52398007-74b54600-2af2-11e9-8b95-fe03c956ee4e.png)
