### ISSUE TITLE
How do i get PTP to work?

### ISSUE THREAD

**Issue by JhoeyPTP** [Microsoft/SDN#308]
I've tried the validation guides, but i'm getting following error codes:
<img width="354" alt="error1" src="https://user-images.githubusercontent.com/47140198/51964773-d11bc400-2467-11e9-98fe-225f594610c3.png">

![capture](https://user-images.githubusercontent.com/47140198/51966297-6b7e0680-246c-11e9-8196-433aeeeb2143.PNG)

Im trying to sync Windows to a embeded system running linux, but it dosent seem to communicate. I see that the embeded systemes are in sync, but the windows unit isent.
All suggestions are welcome, first time using PTP in Windows.

![verbose melding](https://user-images.githubusercontent.com/47140198/51965241-24424680-2469-11e9-98e5-452b010c8b3f.PNG)

**Comment by JhoeyPTP** [comment]
![config](https://user-images.githubusercontent.com/47140198/52326223-2ca9fc80-29e8-11e9-83fa-d7db465d73b3.PNG)

**Comment by JhoeyPTP** [comment]
i've sent you a mail, so we can continue via email.

**Comment by dcuomo** [comment]
Closing as we'll follow-up in email

**Comment by AndreV84** [comment]
same issue here @dcuomo ? any update?
@JhoeyPTP have you been able to resolve the issue over email? what was the solution?

**Comment by Kemler-J** [comment]
@dcuomo @JhoeyPTP  could you help to share the solution? I met the same problem here. 
Thanks a lot

**Comment by dcuomo** [comment]
Hi Folks - @dahavey is the person you need.

**Comment by AndreV84** [comment]
@dahavey never responded anywhere via email/ github etc.
