### ISSUE TITLE
SDNExpress script should use custom DSC resources instead of script resources

### ISSUE THREAD

**Issue by HemantMahawar** [Microsoft/SDN#31]
There are bunch of custom resources available on http://PowerShellGallery.com (with source code on GitHub @ https://github.com/PowerShell/DscResources/tree/master/xDscResources) that should be used instead of script resources such as xVhdFileDirectory, WindowsFeature, xVMHyperV, xFireWall etc.

**Comment by kallie-b** [comment]
@HemantMahawar Any progress here? Is this still an active issue?

**Comment by grcusanz** [comment]
New SDN Express no longer uses DSC.
