### ISSUE TITLE
subnet.env is never created

### ISSUE THREAD

**Issue by celestialorb** [microsoft/SDN#320]
I've followed the guide located here (https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/common-problems) but I can't seem to get flannel to create the subnet.env file.

It never even created the `C:/run/flannel` directory that the file is kept within. I can't seem to figure out what's wrong because there doesn't seem to be any kind of logs left behind.

After a bunch of Googling I believe I've determined the issue is that the `cbr0` network is never created. Flannel is the piece responsible for creating that network, correct? I know that I *always* have to kill flannel initially because it get stuck at "waiting for network to be created", but works just fine the second time. All the documentation states to do is to try running it a second time...

I'm sorry I don't have more info, but that's just honestly what you get when you're forced to use Windows systems; I cannot stress strongly enough how incredibly frustrating working with Windows is.

**Comment by daschott** [comment]
@celestialorb This is on AWS hosted VMs, or where? Note that host-gw mode requires additional configuration on cloud infrastructure for setting up UDRs. For that reason, overlay networking is preferred by most users on cloud providers. On Azure, you can setup UDRs as follows using `az` cli:

My recommendation would be to:
* Clean up all the resources that were created using stop.ps1 & Get-hnsnetwork | remove-hnsnetwork
* Patch your machines to the latest KB patch
* Configure Flannel in overlay (vxlan) networking mode

Please cc me and let me know if you continue hitting the issue where the network and/or subnet.env is not created.

**Comment by celestialorb** [comment]
Closing this as it's old.
