### ISSUE TITLE
Which Priority do we use 5 or 7?

### ISSUE THREAD

**Issue by jlgandy2** [Microsoft/SDN#326]
S2D WS2016_ConvergedNIC_Configuration.docx
"Step 3B: Set policy for Cluster Heartbeats" tells us to set priority tag 7 and in "Step 3F: Validate your settings (optional)" it shows priority 5 as being set NOT 7. Which should it be 7 or 5?

**Comment by devalian** [comment]
I would say 5. Cluster heartbeat is important. 7 is too low priorities to be lost during transit

**Comment by dcuomo** [comment]
Cluster heartbeats can be configured between 5 and 7.  I believe i've resolved the inconsistencies in the documentation (they should all be aligned on 7).

We recommend 7 so that this is the highest numerical TC.
