### ISSUE TITLE
Kubelet.exe on Windows Server Core 1809 - Errors hnsCall Failed in Win32: The object already exits

### ISSUE THREAD

**Issue by GOVYANSONG** [microsoft/SDN#333]
Similar issue has been reported by:

https://github.com/Microsoft/SDN/issues/298
https://github.com/kubernetes/kubernetes/issues/72696
https://github.com/kubernetes/kubernetes/issues/74766

I was able to follow the diagnosis procedure proposed by #74766 and did identity endpoint request to allocate IP occupied by gateway e.g. **10.244.1.2**:

POST
/endpoints/
{"Name":"b084ded9a2c4391e326ac4416f2dc651ea7bc969f17c9407371ea576c8bb810f_cbr0","VirtualNetwork":"0FB28D70-306C-469D-9690-3245A82D882A","Policies":[{"Type":"OutBoundNAT","ExceptionList":["10.96.0.0/12","192.168.29.80/28","10.244.0.0/16"]},{"DestinationPrefix":"10.96.0.0/12","NeedEncap":true,"Type":"ROUTE"},{"DestinationPrefix":"192.168.29.88/32","NeedEncap":true,"Type":"ROUTE"}],"IPAddress":"**10.244.1.2**","DNSSuffix":"default.svc.cluster.local","DNSServerList":"10.96.0.10","GatewayAddress":"**10.244.1.2**"}

The above issue was resolved in https://github.com/kubernetes/kubernetes/pull/74836 for GCE/Windows. My environment is: Windows 10 Hyper-V host, Windows Server 2019 v1809 as Windows VM to host Windows containers, Ubuntu 18.04 to host K8S master node. I am at loss here on how to resolve this issue. It seems that the cluster itself was created correctly but unable to deploy service to Windows node. 

The logs and netsh trace etl file are attached herein: 
[diagnosis.zip](https://github.com/Microsoft/SDN/files/2985627/diagnosis.zip)

**Comment by GOVYANSONG** [comment]
Flannel in Host-GW mode is used on the Windows node. Since Flannel relies on host-local for IPAM, network configuration is passed down to Docker runtime. I skimmed through some source code and if I understood it correctly, IP allocator never allocates the network gateway address e.g. 10.244.1.1. But there is no logic to prevent from allocating 10.244.1.2 (the pod endpoint gateway). It would be possible to avoid allocating 10.244.1.2 by specifying the range start value through IPAM from within Flannel before this information is passed to Docker runtime. 

I am wondering how to resolve this issue since it is blocking us from any meaningful deployment.

**Comment by daschott** [comment]
@GOVYANSONG you need to specify `rangeStart` in host-local config from .3 https://github.com/containernetworking/plugins/tree/master/plugins/ipam/host-local#example-configurations

@nagiesek can this become a default for Flannel host-gw mode?

@GOVYANSONG there is also Flannel overlay networking support now.

**Comment by GOVYANSONG** [comment]
@daschott thanks for the information about configuring ip range for host-local. I will try it once get around.

**Comment by daschott** [comment]
@GOVYANSONG any luck trying it out?

**Comment by GOVYANSONG** [comment]
It has been awhile since original issue was reported. If memory serves me well, I remembered to avoid the allocation of .2 IP by manipulating allocated IP addresses file and at the end the problem disappeared.
