### ISSUE TITLE
Enabling WindowsGMSA support

### ISSUE THREAD

**Issue by dhirschfeld** [microsoft/SDN#338]
According to the documentation [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/#enable-the-windowsgmsa-feature-gate) I need to pass `--feature-gates=WindowsGMSA=true` to `kublet.exe` to enable GMSA support.

Does this mean I need to manually patch `start-kubelet.ps1` to add this argument to the below command?
https://github.com/Microsoft/SDN/blob/f670593b648e974e079b10dfa6ca8c8b307450ce/Kubernetes/windows/start-kubelet.ps1#L117-L124

**Comment by GOVYANSONG** [comment]
Here is how I invoke start.ps1: 

.\start.ps1 -ManagementIP 172.17.57.138 -NetworkMode l2bridge -KubeletFeatureGates WindowsGMSA=true

**Comment by daschott** [comment]
thanks @GOVYANSONG 
@dhirschfeld did that help at all?

**Comment by dhirschfeld** [comment]
I haven't tested it yet, but I'll do so shortly. I'm in the process of updating everything to the latest so when that is done I'll give it a go and report back.

I have high hopes that it will Just Work! ;)

**Comment by daschott** [comment]
OK, sounds good. There is a KEP on gMSA, if it helps at all, it is still an alpha feature and requires v1.14 or higher K8s version:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/20181221-windows-group-managed-service-accounts-for-container-identity.md

**Comment by daschott** [comment]
@dhirschfeld any luck?

**Comment by daschott** [comment]
If at all possible, I would recommend that you post it on SIG-Windows or attend one of the meetings as the folks working on gMSA will be there to address it directly!
https://github.com/kubernetes/community/blob/master/sig-windows/README.md

**Comment by dhirschfeld** [comment]
I think I this worked however shortly thereafter we parked our Windows support to concentrate on the linux side of things until the whole ecosystem surrounding Windows/hybrid k8s clusters matures a little.

I'm happy for this to be closed - the info will still be here for anyone who looks...

**Comment by daschott** [comment]
Thanks for following up, and sorry for the long delay. Feel free to track the recent gMSA work in the KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/20181221-windows-group-managed-service-accounts-for-container-identity.md
