### ISSUE TITLE
Question concerning GMSA support in K8S v1.14

### ISSUE THREAD

**Issue by GOVYANSONG** [microsoft/SDN#339]
I followed the instructions from https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/#assign-role-to-service-accounts-to-use-specific-gmsa-credspecs. Everything went smoothly. But how can I verify that the GMSA account is being applied to the pod/container or configured for IIS?

**Comment by GOVYANSONG** [comment]
https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts

I will try the suggestions and report back my findings.

**Comment by GOVYANSONG** [comment]
In container, tried to verify if GMSA works in windows container with following commands. results are shown below:

PS C:\> nltest /sc_verify:k8s.lab
Flags: 80
Trusted DC Name
Trusted DC Connection Status Status = 1311 0x51f ERROR_NO_LOGON_SERVERS
Trust Verification Status = 1311 0x51f ERROR_NO_LOGON_SERVERS
The command completed successfully

PS C:\> klist get krbtgt

Current LogonId is 0:0x2587c9
Error calling API LsaCallAuthenticationPackage (GetTicket substatus): 0x5

klist failed with 0xc0000022/-1073741790: {Access Denied}
A process has requested access to an object, but has not been granted those access rights.

**Comment by GOVYANSONG** [comment]
Although I can ping both management IP 192.168.142.172 and K8S DNS 10.96.0.10, i could not ping k8s.lab domain name.

**Comment by daschott** [comment]
@GOVYANSONG did you take a look at the gMSA KEP? https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/20181221-windows-group-managed-service-accounts-for-container-identity.md 

Which Windows version and K8s version are you seeing these issues on? It is in alpha only for v1.14 or above.

**Comment by GOVYANSONG** [comment]
@daschott thanks for following up with this matter. I was able to create CredentialSpec as instructed. Also, when I tested within container with netlogon /parentdomain, I was able to get the correct windows domain name. I also observed that the level of AD support varies. For example, I never succeeded to query the AD service from within container among few other attempts. My challenge now is to use the gMSA with my sql server 2017 instance running in docker container. My environment is: windows server 2019 v1809 build 17763, docker EE v18.09.

**Comment by daschott** [comment]
@GOVYANSONG thank you, this is valuable feedback. If at all possible, I would recommend that you post it on SIG-Windows or attend one of the meetings as the folks working on gMSA will be there to address it directly!
https://github.com/kubernetes/community/blob/master/sig-windows/README.md

Also @rpsqrd FYI

**Comment by rpsqrd** [comment]
@GOVYANSONG Just a heads up: we know there are issues when the container host is also the domain controller. You'll need a separate machine to be your domain controller to test gMSA with containers.

**Comment by prawalsharma** [comment]
I see the same issue without my host system being the DC. I might be missing something ?
