### ISSUE TITLE
keep on seeing "Waiting for the Network to be created"

### ISSUE THREAD

**Issue by lixiran** [microsoft/SDN#371]
I am following this guide to add a windows node to a cluster.
https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/joining-windows-workers.
after running the start.ps1. it keep on showing below message:
VERBOSE: Invoke-HNSRequest Method[GET] Path[/networks] Data[]
VERBOSE: Result : { "Output" : [<ignore the data>]}
Waiting for the Network to be created

anyone see this ?

**Comment by lixiran** [comment]
the log throw this error:

Error registering network: Cannot get HNS networks [hcnEnumerateNetworks failed in Win32: The specified module could not be found

**Comment by lanzhiwang** [comment]
I am following this guide to add a windows node to a cluster.
https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/joining-windows-workers.
after running the start.ps1. it keep on showing below message:
PS C:\k> .\start.ps1 -ManagementIP eth0  -NetworkMode overlay  -ClusterCIDR 172.20.0.0/16 -ServiceCIDR 10.68.0.0/16 -KubeDnsServiceIP 10.68.0.2  -LogDir F:\k8s\kubernetes\node\bin\log
Creating Kubernetes directories
Downloading Windows Kubernetes scripts
File c:\k\hns.psm1 already exists.
File c:\k\Dockerfile already exists.
File c:\k\stop.ps1 already exists.
File c:\k\start-kubelet.ps1 already exists.
File c:\k\start-Kubeproxy.ps1 already exists.
Downloading Flannel binaries
File c:\k\flanneld.exe already exists.
Downloading CNI binaries
File c:\k\net-conf.json already exists.
File c:\k\cni\config\cni.conf already exists.
File c:\k\cni\flannel.exe already exists.
File c:\k\cni\host-local.exe already exists.
File c:\k\cni\win-overlay.exe already exists.
Copying Flannel setup files
警告: 模块“hns”中的某些导入命令的名称包含未批准的动词，这些动词可能导致这些命令名不易被发现。若要查找具有未批准的动词的命令，请使用 Verbose 参数再次运行 Import-Module 命令。有关批准的动词列表，请键入 Get-Verb。
Generated CNI Config [@{cniVersion=0.2.0; name=vxlan0; type=flannel; delegate=}]
Generated net-conf Config [@{Network=172.20.0.0/16; Backend=}]
Node k8s-win-worker1 already registered
警告: 模块“hns”中的某些导入命令的名称包含未批准的动词，这些动词可能导致这些命令名不易被发现。若要查找具有未批准的动词的命令，请使用 Verbose 参数再次运行 Import-Module 命令。有关批准的动词列表，请键入 Get-Verb。
详细信息: Invoke-HNSRequest Method[GET] Path[/networks] Data[]
详细信息: Result :
{"Output":[{"ActivityId":"84473089-EDC9-436D-A1E1-3A7882850FD5","AdditionalParams":{},"CurrentEndpointCount":0,"DNSServerCompartment":3,"DrMacAddress":"00-15-5D-BB-6E-B1","Extensions":[{"Id":"E7C3B2F0-F3C5-48DF-AF2B-10FED6D72E7A","IsEnabled":false,"Name":"Microsoft
Windows 筛选平台"},{"Id":"E9B59CFA-2BE1-4B21-828F-B6FBDBDDC017","IsEnabled":true,"Name":"Microsoft Azure VFP Switch Extension"},{"Id":"EA24CD6C-D17A-4348-9190-09F0D5BE83DD","IsEnabled":true,"Name":"Microsoft NDIS
捕获"}],"Flags":0,"Health":{"LastErrorCode":0,"LastUpdateTime":132062804690677089},"ID":"9B219D6E-6847-43FC-8258-81DB4B63C09C","IPv6":false,"LayeredOn":"395B983F-DCC7-4E77-BF04-F01084CFC7DD","MacPools":[{"EndMacAddress":"00-15-5D-69-3F-FF","StartMacAddress":"00-15-5D-69
-30-00"}],"ManagementIP":"10.1.36.50","MaxConcurrentEndpoints":0,"Name":"External","Policies":[],"Resources":{"AdditionalParams":{},"AllocationOrder":0,"Allocators":[{"AdditionalParams":{},"AllocationOrder":0,"Health":{"LastErrorCode":0,"LastUpdateTime":1320628046872396
02},"ID":"2D72E7C0-9E9D-4A01-8057-66E7938D0EE0","IsPolicy":false,"Isolation_0":9999,"PortId":"81C0D794-C201-4707-9D12-F1AF435C1916","RDID":"9B219D6E-6847-43FC-8258-81DB4B63C09C","State":3,"SwitchId":"30081EA2-DE0E-4771-82BF-3FDBE9AA31BB","Tag":"RDID"}],"Health":{"LastEr
rorCode":0,"LastUpdateTime":132062804687239602},"ID":"84473089-EDC9-436D-A1E1-3A7882850FD5","PortOperationTime":0,"State":1,"SwitchOperationTime":0,"VfpOperationTime":0,"parentId":"325555C6-D065-4A90-A92A-DD7A5EED5B9B"},"State":1,"Subnets":[{"AdditionalParams":{},"Addre
ssPrefix":"192.168.255.0/30","GatewayAddress":"192.168.255.1","Health":{"LastErrorCode":0,"LastUpdateTime":132062804690677089},"ID":"A8D5A7AB-DD0D-4A01-8E37-10681D2A494A","ObjectType":5,"Policies":[{"Type":"VSID","VSID":9999}],"State":0}],"TotalEndpoints":0,"Type":"over
lay","Version":38654705666},{"ActivityId":"D50207B0-EE01-422B-A50F-0335E1F4DED4","AdditionalParams":{},"CurrentEndpointCount":0,"Extensions":[{"Id":"E7C3B2F0-F3C5-48DF-AF2B-10FED6D72E7A","IsEnabled":false,"Name":"Microsoft Windows
筛选平台"},{"Id":"E9B59CFA-2BE1-4B21-828F-B6FBDBDDC017","IsEnabled":false,"Name":"Microsoft Azure VFP Switch Extension"},{"Id":"EA24CD6C-D17A-4348-9190-09F0D5BE83DD","IsEnabled":true,"Name":"Microsoft NDIS
捕获"}],"Flags":0,"Health":{"AddressNotificationMissedCount":0,"AddressNotificationSequenceNumber":0,"InterfaceNotificationMissedCount":0,"InterfaceNotificationSequenceNumber":0,"LastErrorCode":0,"LastUpdateTime":132062804742629962,"RouteNotificationMissedCount":0,"Rout
eNotificationSequenceNumber":0},"ID":"06D51CD5-A6D0-4B6A-B77E-86F05F64DF6F","IPv6":false,"LayeredOn":"9630961E-8862-4E8D-A62A-ACF8267BFDA9","MacPools":[{"EndMacAddress":"00-15-5D-EE-FF-FF","StartMacAddress":"00-15-5D-EE-F0-00"}],"MaxConcurrentEndpoints":0,"Name":"nat","
NatName":"ICS0EC878AE-D78E-411C-A266-679E9637F485","Policies":[],"Resources":{"AdditionalParams":{},"AllocationOrder":2,"Allocators":[{"AdapterNetCfgInstanceId":"{0EC878AE-D78E-411C-A266-679E9637F485}","AdditionalParams":{},"AllocationOrder":0,"CompartmendId":0,"Connect
ed":true,"DevicelessNic":false,"EndpointNicGuid":"DC9C38B9-EB43-44CD-8170-0195F5318BD3","EndpointPortGuid":"A30EABD5-A1D5-4BBF-8FD0-C5CD2B46BD95","Health":{"LastErrorCode":0,"LastUpdateTime":132062804744873285},"Hidden":false,"ID":"81A8FE90-6A84-460D-A87C-1DB61F4FE1D8",
"InterfaceGuid":"0EC878AE-D78E-411C-A266-679E9637F485","IsPolicy":false,"IsolationId":0,"MTU":1450,"MacAddress":"00-15-5D-EE-F0-10","ManagementPort":true,"NicFriendlyName":"nat","PreferredPortFriendlyName":"Container NIC
81a8fe90","State":3,"SwitchId":"9B2F9B08-FB83-4F22-A79F-A9A94416C640","Tag":"Host
Vnic","WaitForIpv6Interface":false,"nonPersistentPort":false},{"AdditionalParams":{},"AllocationOrder":1,"Dhcp":false,"Dns":false,"ExternalInterfaceConstraint":0,"Health":{"DHCPState":1,"DNSState":1,"ICSState":2,"LastErrorCode":0,"LastUpdateTime":132062804747841890},"IC
SFlags":0,"ID":"5C220452-4FED-43DC-ABA3-E13187829C68","IsPolicy":false,"Prefix":20,"PrivateInterfaceGUID":"0EC878AE-D78E-411C-A266-679E9637F485","State":3,"SubnetIPAddress":"172.28.0.0","Tag":"ICS"}],"Health":{"LastErrorCode":0,"LastUpdateTime":132062804744716906},"ID":
"D50207B0-EE01-422B-A50F-0335E1F4DED4","PortOperationTime":0,"State":1,"SwitchOperationTime":0,"VfpOperationTime":0,"parentId":"66C18C2A-2156-427C-A529-7992BB1FBC20"},"State":1,"Subnets":[{"AdditionalParams":{},"AddressPrefix":"172.28.0.0/20","GatewayAddress":"172.28.0.
1","Health":{"LastErrorCode":0,"LastUpdateTime":132062804744873285},"ID":"D63E42C4-DB75-46D5-AC97-18FDA37CE4B1","Policies":[],"State":0}],"TotalEndpoints":0,"Type":"nat","Version":38654705666}],"Success":true}
Waiting for the Network to be created
I0701 01:35:53.648966     776 main.go:210] Could not find valid interface matching eth0: failed to find IPv4 address for interface eth0
E0701 01:35:53.648966     776 main.go:234] Failed to find interface to use that matches the interfaces and/or regexes provided
详细信息: Invoke-HNSRequest Method[GET] Path[/networks] Data[]
详细信息: Result :
{"Output":[{"ActivityId":"84473089-EDC9-436D-A1E1-3A7882850FD5","AdditionalParams":{},"CurrentEndpointCount":0,"DNSServerCompartment":3,"DrMacAddress":"00-15-5D-BB-6E-B1","Extensions":[{"Id":"E7C3B2F0-F3C5-48DF-AF2B-10FED6D72E7A","IsEnabled":false,"Name":"Microsoft
Windows 筛选平台"},{"Id":"E9B59CFA-2BE1-4B21-828F-B6FBDBDDC017","IsEnabled":true,"Name":"Microsoft Azure VFP Switch Extension"},{"Id":"EA24CD6C-D17A-4348-9190-09F0D5BE83DD","IsEnabled":true,"Name":"Microsoft NDIS
捕获"}],"Flags":0,"Health":{"LastErrorCode":0,"LastUpdateTime":132062804690677089},"ID":"9B219D6E-6847-43FC-8258-81DB4B63C09C","IPv6":false,"LayeredOn":"395B983F-DCC7-4E77-BF04-F01084CFC7DD","MacPools":[{"EndMacAddress":"00-15-5D-69-3F-FF","StartMacAddress":"00-15-5D-69
-30-00"}],"ManagementIP":"10.1.36.50","MaxConcurrentEndpoints":0,"Name":"External","Policies":[],"Resources":{"AdditionalParams":{},"AllocationOrder":0,"Allocators":[{"AdditionalParams":{},"AllocationOrder":0,"Health":{"LastErrorCode":0,"LastUpdateTime":1320628046872396
02},"ID":"2D72E7C0-9E9D-4A01-8057-66E7938D0EE0","IsPolicy":false,"Isolation_0":9999,"PortId":"81C0D794-C201-4707-9D12-F1AF435C1916","RDID":"9B219D6E-6847-43FC-8258-81DB4B63C09C","State":3,"SwitchId":"30081EA2-DE0E-4771-82BF-3FDBE9AA31BB","Tag":"RDID"}],"Health":{"LastEr
rorCode":0,"LastUpdateTime":132062804687239602},"ID":"84473089-EDC9-436D-A1E1-3A7882850FD5","PortOperationTime":0,"State":1,"SwitchOperationTime":0,"VfpOperationTime":0,"parentId":"325555C6-D065-4A90-A92A-DD7A5EED5B9B"},"State":1,"Subnets":[{"AdditionalParams":{},"Addre
ssPrefix":"192.168.255.0/30","GatewayAddress":"192.168.255.1","Health":{"LastErrorCode":0,"LastUpdateTime":132062804690677089},"ID":"A8D5A7AB-DD0D-4A01-8E37-10681D2A494A","ObjectType":5,"Policies":[{"Type":"VSID","VSID":9999}],"State":0}],"TotalEndpoints":0,"Type":"over
lay","Version":38654705666},{"ActivityId":"D50207B0-EE01-422B-A50F-0335E1F4DED4","AdditionalParams":{},"CurrentEndpointCount":0,"Extensions":[{"Id":"E7C3B2F0-F3C5-48DF-AF2B-10FED6D72E7A","IsEnabled":false,"Name":"Microsoft Windows
筛选平台"},{"Id":"E9B59CFA-2BE1-4B21-828F-B6FBDBDDC017","IsEnabled":false,"Name":"Microsoft Azure VFP Switch Extension"},{"Id":"EA24CD6C-D17A-4348-9190-09F0D5BE83DD","IsEnabled":true,"Name":"Microsoft NDIS
捕获"}],"Flags":0,"Health":{"AddressNotificationMissedCount":0,"AddressNotificationSequenceNumber":0,"InterfaceNotificationMissedCount":0,"InterfaceNotificationSequenceNumber":0,"LastErrorCode":0,"LastUpdateTime":132062804742629962,"RouteNotificationMissedCount":0,"Rout
eNotificationSequenceNumber":0},"ID":"06D51CD5-A6D0-4B6A-B77E-86F05F64DF6F","IPv6":false,"LayeredOn":"9630961E-8862-4E8D-A62A-ACF8267BFDA9","MacPools":[{"EndMacAddress":"00-15-5D-EE-FF-FF","StartMacAddress":"00-15-5D-EE-F0-00"}],"MaxConcurrentEndpoints":0,"Name":"nat","
NatName":"ICS0EC878AE-D78E-411C-A266-679E9637F485","Policies":[],"Resources":{"AdditionalParams":{},"AllocationOrder":2,"Allocators":[{"AdapterNetCfgInstanceId":"{0EC878AE-D78E-411C-A266-679E9637F485}","AdditionalParams":{},"AllocationOrder":0,"CompartmendId":0,"Connect
ed":true,"DevicelessNic":false,"EndpointNicGuid":"DC9C38B9-EB43-44CD-8170-0195F5318BD3","EndpointPortGuid":"A30EABD5-A1D5-4BBF-8FD0-C5CD2B46BD95","Health":{"LastErrorCode":0,"LastUpdateTime":132062804744873285},"Hidden":false,"ID":"81A8FE90-6A84-460D-A87C-1DB61F4FE1D8",
"InterfaceGuid":"0EC878AE-D78E-411C-A266-679E9637F485","IsPolicy":false,"IsolationId":0,"MTU":1450,"MacAddress":"00-15-5D-EE-F0-10","ManagementPort":true,"NicFriendlyName":"nat","PreferredPortFriendlyName":"Container NIC
81a8fe90","State":3,"SwitchId":"9B2F9B08-FB83-4F22-A79F-A9A94416C640","Tag":"Host
Vnic","WaitForIpv6Interface":false,"nonPersistentPort":false},{"AdditionalParams":{},"AllocationOrder":1,"Dhcp":false,"Dns":false,"ExternalInterfaceConstraint":0,"Health":{"DHCPState":1,"DNSState":1,"ICSState":2,"LastErrorCode":0,"LastUpdateTime":132062804747841890},"IC
SFlags":0,"ID":"5C220452-4FED-43DC-ABA3-E13187829C68","IsPolicy":false,"Prefix":20,"PrivateInterfaceGUID":"0EC878AE-D78E-411C-A266-679E9637F485","State":3,"SubnetIPAddress":"172.28.0.0","Tag":"ICS"}],"Health":{"LastErrorCode":0,"LastUpdateTime":132062804744716906},"ID":
"D50207B0-EE01-422B-A50F-0335E1F4DED4","PortOperationTime":0,"State":1,"SwitchOperationTime":0,"VfpOperationTime":0,"parentId":"66C18C2A-2156-427C-A529-7992BB1FBC20"},"State":1,"Subnets":[{"AdditionalParams":{},"AddressPrefix":"172.28.0.0/20","GatewayAddress":"172.28.0.
1","Health":{"LastErrorCode":0,"LastUpdateTime":132062804744873285},"ID":"D63E42C4-DB75-46D5-AC97-18FDA37CE4B1","Policies":[],"State":0}],"TotalEndpoints":0,"Type":"nat","Version":38654705666}],"Success":true}
Waiting for the Network to be created

**Comment by daschott** [comment]
@lixiran can you please apply the latest KB and try again? Please cc me and let me know if you continue hitting this "Waiting for network to be created". Thanks!

**Comment by nocanstillbb** [comment]
> @lixiran can you please apply the latest KB and try again? Please cc me and let me know if you continue hitting this "Waiting for network to be created". Thanks!
i have a seme problem now,   
10.0.17763.1158
![image](https://user-images.githubusercontent.com/22405678/79887742-f199ba80-842d-11ea-927e-5228af176c03.png)

**Comment by nocanstillbb** [comment]
> @lixiran can you please apply the latest KB and try again? Please cc me and let me know if you continue hitting this "Waiting for network to be created". Thanks!
i have a seme problem now,   
10.0.17763.1158
![image](https://user-images.githubusercontent.com/22405678/79887742-f199ba80-842d-11ea-927e-5228af176c03.png)

**Comment by masaeedu** [comment]
@daschott What's the latest KB that you're referring to? I've applied all the updates Windows Update was able to find using sconfig, but the problem persists. I wasn't able to find KB4489899 in the list of installed hotfixes though, and attempting to install it manually indicates "this update is not applicable to your computer".

**Comment by daschott** [comment]
Ah, the instructions have changed a lot over the time. The old doc on docs.microsoft.com is being removed next week. New instructions are maintained by community and can be found here:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/
 
This issue should be resolved with Flannel daemonset approach. If you encounter a problem with new docs, please file an issue under sig-windows tools repo https://github.com/kubernetes-sigs/sig-windows-tools/issues
