### ISSUE TITLE
SDN WS2019 + SCVMM2019

### ISSUE THREAD

**Issue by chmody255** [microsoft/SDN#387]
Hi Guys

Trying to setup SDN on WS2019 + SCVMM2019 having endless problems.
Has anyone done this yet is it supported?

**Comment by wangkanai** [comment]
Same problem here also. Microsoft Support is have issue supporting SDN with Windows Server 2019 and System Center Virtual Machine Manager 2019 also.

Upgrade cause failure and reinstall one bug after another.

**Comment by nagiesek** [comment]
@daschott - I'm not sure about what you're trying to do.

**Comment by daschott** [comment]
@nnamuhcs FYI

**Comment by grcusanz** [comment]
Anyone that is still having issues, please try with the latest SCVMM UR, latest VMM service templates/VMM SDN Express.  Then, follow up with specific details on the issue you are encountering.
