### ISSUE TITLE
The Name of the folder the SDN VMs are created make it difficult for Cluster Operations

### ISSUE THREAD

**Issue by perfycat** [microsoft/SDN#410]
The name of the folder the SDN VMs are created look like : Virtual Machine (Name - 'xxx-NC-02') [Id = 'someguide'].Name.

All the spaces and single quotes make it difficult to manage this later in scripts.  Can a more simple name be applied.

**Comment by grcusanz** [comment]
Unable to repro.  VM folders are based on the VM name that is passed into SDN express.  Make sure you are passing in the correct VM name.
