### ISSUE TITLE
Problem TP5 SLB

### ISSUE THREAD

**Issue by bmis** [Microsoft/SDN#44]
Hi, 

I have this problem when I use SDNExpress script

add-windowsfeature : ArgumentNotValid: The role, role service, or feature name is not valid: 'SoftwareLoadBalancer'. The name was not  found.
At line:1 char:1
+ add-windowsfeature SoftwareLoadBalancer 

any idea?

Thanks

**Comment by nwoodmsft** [comment]
Hi,

The current 'master' version of the SDNExpress scripts has moved beyond TP5. The change you mentioned (SoftwareLoadBalancer being a Windows Feature) was not present in TP5 builds of Windows Server.

If you need a TP5-aligned copy of the SDNExpress script, then you may use the TP5 branch: https://github.com/Microsoft/SDN/tree/TP5

Thank you,
