### ISSUE TITLE
Service slbmux was not found on computer 

### ISSUE THREAD

**Issue by devalian** [Microsoft/SDN#47]
When i was trying to deploy SLB using SCVMM RTM 2016. 

i was hit with multiple issue. First of all, registry was not found. Im using WS2016 RTM hyperbase.
VERBOSE: [2016-10-09T21:15:41.1898573+08:00]  Adding Network Controller Certificates to trusted Root Store
VERBOSE: [2016-10-09T21:15:41.2210983+08:00] Found certificate at path: C:\MuxInstall\NCCertificate\MultiNodeNC.cer
VERBOSE: [2016-10-09T21:15:41.2210983+08:00] Adding certificate to root store..
VERBOSE: [2016-10-09T21:15:41.2999737+08:00] Extracting subject Name from Certificate 
VERBOSE: [2016-10-09T21:15:41.3156151+08:00] Parsing Subject Name CN=172.16.1.30 to get Subject Fqdn 
VERBOSE: [2016-10-09T21:15:41.3156151+08:00] Updating registry values for Mux...
VERBOSE: [2016-10-09T21:15:50.6066217+08:00] Caught an exception:
VERBOSE: [2016-10-09T21:15:50.6339225+08:00]     Exception Type: System.Management.Automation.ItemNotFoundException
VERBOSE: [2016-10-09T21:15:50.6495633+08:00]     Exception Message: Cannot find path 
'HKLM:\SYSTEM\CurrentControlSet\Services\SlbMux' because it does not exist.
VERBOSE: [2016-10-09T21:15:50.6651894+08:00]     Excepti"

Secondly, SLBMUX services was not installed by the script.
VERBOSE: [2016-10-09T21:22:11.1207763+08:00] Setting slbmux service to autostart
VERBOSE: [2016-10-09T21:22:11.1676501+08:00] Caught an exception:
VERBOSE: [2016-10-09T21:22:11.1989009+08:00]     Exception Type: System.InvalidOperationException
VERBOSE: [2016-10-09T21:22:11.2145245+08:00]     Exception Message: Service slbmux was not found on computer '.'.
VERBOSE: [2016-10-09T21:22:11.2145245+08:00]     Excepti"

anyone can help me where did i did wrong?

Thanks

**Comment by manishmsft** [comment]
Hello, it appears that you are using older Service Templates from TP5 timeline which are not compatible with VMM 2016 RTM build. Could you use the newer Service Templates uploaded earlier this week on Github and retry the scenarios? All the issues reported by you are fixed in the new instance of the SLB Service Template.
