### ISSUE TITLE
The term '\Scripts\CertHelpers.ps1' is not recognized...

### ISSUE THREAD

**Issue by benpiper** [Microsoft/SDN#50]
After the SDNExpress.ps1 script gets to the "End Set" portion of `InstallHostCert`, I get the following error:

`PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: The term '\Scripts\CertHelpers.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. `

**Comment by nwoodmsft** [comment]
Offhand, it looks like you are missing a value for the HostInstallSrcDir variable. The script is trying to access:

> $($using:node.HostInstallSrcDir)\Scripts\CertHelpers.ps1

The HostInstallSrcDir is a variable configured at the very top of the FabricConfig.psd1 file. Please check that config file and ensure that you have HostInstallSrcDir defined. In most deployments the value will be set to the same value as InstallSrcDir.

Note: HostInstallSrcDir was introduced in the RTM/Master branch copy of FabricConfig.psd1. If you are using an older (e.g. TP5) version of the FabricConfig.psd1 file with the RTM version of the scripts, there will be problems and mismatches like this. It is strongly recommended to start over with a fresh copy of FabricConfig.psd1 from the Master branch.
