### ISSUE TITLE
ConfigureSLBManager doesn't select the correct logical network if multiple logical networks use the same subnet

### ISSUE THREAD

**Issue by benpiper** [Microsoft/SDN#52]
[ConfigureSLBManager](https://github.com/Microsoft/SDN/blob/master/SDNExpress/scripts/SDNExpress.ps1#L1475) doesn't select the correct logical network if multiple logical networks use the same subnet. The FabricConfig example states that this is allowed (https://github.com/Microsoft/SDN/blob/master/SDNExpress/scripts/FabricConfig.example.psd1#L59)

It looks like the script locates all subnets that have a VIP pool. It then iterates through each logical network until it finds one with a matching subnet. In the case of multiple logical networks using the same subnet, the script always selects the logical network with the lowest resource reference, even though that may not be the correct logical network. See https://github.com/Microsoft/SDN/blob/master/SDNExpress/scripts/SDNExpress.ps1#L1484-L1522)

To give an example: I have two logical networks as VIP pools: PublicVIP (192.168.3.0/24 with a pool of 3.120-3.159) and PrivateVIP (192.168.3.0/24 with a pool of 3.160-3.199).

I also have a Transit logical network (not a VIP pool) with a pool of 3.80-3.119. The resource reference ID is 00000000-2222-1111-9999-000000000001, which is the lowest of all logical networks. The script selects 192.168.3.80 as the SLMBVIP because the Transit logical network is the first one it falls on with a matching subnet.

**Comment by JMesser81** [comment]
@nwoodmsft

**Comment by JMesser81** [comment]
Hi Ben - sorry for the LONG delay on this. Are you still having this issue?
