### ISSUE TITLE
Unattend files hardcode timezone and user locale

### ISSUE THREAD

**Issue by nwoodmsft** [Microsoft/SDN#53]
The script has hardcoded values for timezone and user locale which are applied to the fabric and tenant VMs via unattend. These values may need to be changed for some deployments and we should therefore expose them via FabricConfig/TenantConfig instead of hardcoding them within the SDNExpress ps1 scripts.

**Comment by kallie-b** [comment]
Any progress here? Is this still an active issue?

**Comment by grcusanz** [comment]
SDNExpress has been updated to use the locale and timezone of the host by default.  They can also be overridden in the config file.  The tenant example script will soon be deprecated in favor of simpler example snippets.
