### ISSUE TITLE
VM traffic being sent over PA network

### ISSUE THREAD

**Issue by DCoates-InnovateLtd** [microsoft/SDN#576]
Good morning, 

Please can someone help me? I have deployed Azure HCI and used the SDN Express powershell to deploy the SDN. this ran though successfully with no errors. I have connected a device to the MUX and GWs using BGP and i can see advertised routes. when i have built a VNET in WAC and a subnet built a basic VM and attached to the subnet if i ping 8.8.8.8 for example i can see the traffic running accross the PA network but with out the VMs Public IP address. it shows up as the VMs private IP. Am i supposed to provide NAT in addition to the SDN Express deployment? or should i expect that the PA network would only pass public ipaddresses? 

Thanks for the help. i have attached the config file. 
[SDNDeploymentv1.1.txt](https://github.com/microsoft/SDN/files/11541593/SDNDeploymentv1.1.txt)

**Comment by AnirbanPaul** [comment]
Pascal is right. You have two options:
1. Attach a public IP address directly to a VM. You can do so by going to the VM Network Properties in Windows Admin Center and assign a public IP address there.
2. Configure a load balancer. In the load balancer, create an outbound NAT rule. Ensure that you add the VM NIC in the backend pool of the load balancer. More details here: https://learn.microsoft.com/en-us/azure-stack/hci/manage/load-balancers
