### ISSUE TITLE
MUX outbound nat ICMP Problem

### ISSUE THREAD

**Issue by DanivosYoun** [microsoft/SDN#595]
Hi,

Recent i did deployment, for P.O.C of Microsoft SDN

but when i try to make outbound nat (LB) there is only, TCP / UDP Protocol

there is no way to ICMP (ping) to outbound network?

Regards

**Comment by DCoates-InnovateLtd** [comment]
Hi Danivos, 

I have had the same issue. This is because the MS LB's work at layer 4 and up, and so cannot ping. very frustrating. but a feature not a bug.

**Comment by DanivosYoun** [comment]
> Hi Danivos, 
> 
> 
> 
> I have had the same issue. This is because the MS LB's work at layer 4 and up, and so cannot ping. very frustrating. but a feature not a bug. 

Thank you for kindly response,
Can i ask one more things?
I deployed sdn already but i can't find how can i add hyper-v host to sdn enviroments

**Comment by DCoates-InnovateLtd** [comment]
not sure i understand the question? how have you deployed the current SDN environment? what OS are you using in both environments?
