### ISSUE TITLE
Disable Restart Manager in NC for Windows Server RTM - Critical Issue!

### ISSUE THREAD

**Issue by BlackMorokei** [Microsoft/SDN#60]
With the recent changes in the PrepareNodeForNetworkController.ps1 there is a critical issue.
The powershell script is looking on the network controller under C:\Windows\NetworkController in the TemplateClusterManifest.xml for the XML version number. The version number is the 10.1.0.0. In the powershell script it throws an error because it is the version 10.1.0.0.

Here is the snippet of the PrepareNodeForNetworkController.ps1 file.
[versionCheckSnippet.txt](https://github.com/Microsoft/SDN/files/600088/versionCheckSnippet.txt)

Please make sure that the version number of the TemplateClusterManifest.xml is changed.

**Comment by JMesser81** [comment]
I believe v10.1.0.0 of this Service Fabric manifest had a bug. There was a temporary fix to disable Restart Manager but this was not tenable long-term. 

Did you update to the latest Windows Server 2016 patches? KB3197954 The NC VM (VHDX) needs to be patched with this before deploying NC Template

**Comment by BlackMorokei** [comment]
Thanks for the quick answer. Yes I updated the VHD/X. I've tried it many times but I still have this bug.
It workes for me when I disable the code.

**Comment by JMesser81** [comment]
I'm looking into this... Could you please run PS > Get-HotFix and copy-paste the output here

**Comment by BlackMorokei** [comment]
Sure. I will do it as fast as possible.

**Comment by BlackMorokei** [comment]
This is strange. There is only one update installed.
Source        Description      HotFixID      InstalledBy          InstalledOn                        
NC01          Update             KB3192137                             9/12/2016 12:00:00 AM    

And on my full patched SCVMM Server there is only one update too.
I will patch the VHD/X again. Hopefully there are more updates.

**Comment by BlackMorokei** [comment]
So now I have all updates. The update KB3197954 was replaced with the KB3200970.
Source       Description         HotFixID         InstalledBy                        InstalledOn
TEST          Update                KB3192137                                              9/12/2016 12:00:00 AM
TEST          Update                KB3199986     TEST\Administrator          11/18/2016 12:00:00 AM
TEST          Security Update  KB3200970     NT AUTHORITY\SYSTEM  11/18/2016 12:00:00 AM

**Comment by BlackMorokei** [comment]
With all updates it's working fine. Thanks for help.

**Comment by JMesser81** [comment]
Great, glad it's working.
