### ISSUE TITLE
Is it possible to use the VMM SDN Script to deploy SLB and GW after the Network Controller Installation?

### ISSUE THREAD

**Issue by DNigussie** [microsoft/SDN#608]
Hello,

After deploying the network controller using VMM SDN Express, is it possible to use the VMM SDN Express script to install the SLB and GW?

What other option do I have to install the SLB and GW to use the already created NC nodes? 

Thanks,
Dereje

**Comment by The-TeQnician** [comment]
Technically it is possible, but you have to tweak the script a lot to make it work. And for what i know the script is not really intended for that. Best to redeploy all and add SLB/GW to the setup from the start. Otherwise it a manual process.

**Comment by DNigussie** [comment]
I tried it and it worked. Thanks
