### ISSUE TITLE
Trouble deploying NC

### ISSUE THREAD

**Issue by Sunsh1ne9874** [microsoft/SDN#610]
Hello,

how do I get past the error when deploying NC (with sdnExpress or WAC): _Software Defined Networking (SDN) requires an OS containing Windows Server 2016 Datacenter, Windows Server 2019 Datacenter, or Azure Stack HCI."_ ?

I did the HCI cluster with 2022, 2025 and azure hci and always the same error, no matter what I do.

Also, I deployed NC with powershell successfully, and when I try to add it to WAC, it fails and logs sdn-wac-validation-cert.log show:
attempting to query sdn networkController

TY

**Comment by AnirbanPaul** [comment]
Hi
Which OS version vhdx file did you supply to SDN Express (or WAC)? You mention that it was not working, but later you were able to deploy NC. How did you fix the problem?

For the WAC issue, can you share the log file.

**Comment by Sunsh1ne9874** [comment]
When I enter the controller REST UI and click Validate, It shows me screen on the pic:
![image](https://github.com/user-attachments/assets/1aa80966-14ee-4b94-bd1e-e2658ef69fe2)
Then it shows: _Validating other SDN configuration...._ 
And right after that: _Windows Admin Center ran into unexpected error during validation of the Windows Server Network Controller. More information may be found in the users documents directory on the WAC gateway._

Only these 2 logs appear in documents on WAC server:
[sdn-wac-validation-rsat.log](https://github.com/user-attachments/files/16519316/sdn-wac-validation-rsat.log)
[sdn-wac-validation-cert.log](https://github.com/user-attachments/files/16519317/sdn-wac-validation-cert.log)

**Comment by Sunsh1ne9874** [comment]
I managed to install now through WAC. I had to convert some non-evaluation iso into vhdx and now it's OK.

**Comment by AnirbanPaul** [comment]
Are you still seeing the WAC issue?

**Comment by Sunsh1ne9874** [comment]
That issue was resolved. Thank you.

But now I have another issue, Logical Networks tab doesn't open:

![image](https://github.com/user-attachments/assets/582db6a7-a956-4d64-b759-1f3cd2aff17e)

I updated all servers with Windows update.

NC seems to work fine:

![image](https://github.com/user-attachments/assets/31d0d0c8-4765-4e15-a147-c0af8118ff3c)

**Comment by Sunsh1ne9874** [comment]
OK, I deployed NC 2022 with SDNExpress scripts (it didn't work with WAC) on 2022 HCI cluster and now it is working. 

Thank you
