### ISSUE TITLE
VMMExpress fails due to incorrect template file structure

### ISSUE THREAD

**Issue by slavizh** [Microsoft/SDN#63]
Folders EdgeDeployment.cr and NCCertificate.cr needs to be moved from Templates\NC to Templates SLB.

**Comment by BlackMorokei** [comment]
This is irrelevant because you can import the .cr from anywhere. You need all .cr for a functioning SDN infrastructure.

**Comment by slavizh** [comment]
Why is irrelevant. This script should work out of the box without any issues.

**Comment by sanjkum** [comment]
This is fixed and pushed in as part of VMMExpress last iteration. Please close the issue if you see that the issue is addressed.

**Comment by slavizh** [comment]
Closing. Thanks for fixing it.
