### ISSUE TITLE
The code for creating NC domain account is incorrect

### ISSUE THREAD

**Issue by slavizh** [Microsoft/SDN#64]
The code from line 439 till 442 looks like this:
# Create the Local Admin Run As Account
	$MgmtDomainCredPassword = ConvertTo-SecureString -String $node.ManagementDomainUserPassword -Force -AsPlainText
	$MgmtDomainCred = New-Object System.Management.Automation.PSCredential ($node.ManagementDomainUser, $localAdminCredPassword)
	$MgmtAdminRAA = New-SCRunAsAccount -Name "NC_MgmtAdminRAA" -Credential $MgmtDomainCred

It should be changed to this:
# Create NC domain admin Run As Account
	$MgmtDomainCredPassword = ConvertTo-SecureString -String $node.ManagementDomainUserPassword -Force -AsPlainText
	$MgmtDomainCred = New-Object System.Management.Automation.PSCredential ($node.ManagementDomainUser, $MgmtDomainCredPassword)
	$MgmtAdminRAA = New-SCRunAsAccount -Name "NC_MgmtAdminRAA" -Credential $MgmtDomainCred

**Comment by sanjkum** [comment]
This is fixed in the current iteration of VMMExpress. Please close the issue if you see it addressed.

**Comment by slavizh** [comment]
Thanks for fixing it. Closing.
