### ISSUE TITLE
VMMExpress - Function undoNCDeployment does not work as it is trying to remove Run As accounts before other resources are removed first

### ISSUE THREAD

**Issue by slavizh** [Microsoft/SDN#65]
Function undoNCDeployment does not work as it is trying to remove Run As accounts before other resources are removed first.
First the Service and Service instances needs to be removed.
Then the Service Template.
Then the resources in the library
Then Run As Accounts.

**Comment by slavizh** [comment]
Seems issue is related to incorrect variables:
```powershell
#Remove the NC service instance
        $SCService = get-SCService -Name "NC"
        if($SCServic.count -gt 0)
        {
            Remove-SCService -Service $SCService
        }
        
        #Remove service Template
        $ServiceTemplate = Get-SCServiceTemplate -Name "NC Deployment service Template"
        if($ServiceTemplat.count -gt 0)
        {
            Remove-SCServiceTemplate -ServiceTemplate $ServiceTemplate
        }

```
Example $SCService and $SCServic.count

**Comment by JMesser81** [comment]
ping @manishmsft

**Comment by manishmsft** [comment]
Thanks @JMesser81 and @slavizh . Our team is taking a look at this and we will update you once its investigated.

**Comment by slavizh** [comment]
Ok. I guess you will make a change to fix the script.
