### ISSUE TITLE
VMMExpress - NC tempaltes have setting for deploying to Local Storage

### ISSUE THREAD

**Issue by slavizh** [Microsoft/SDN#66]
NC Templates in https://github.com/Microsoft/SDN/blob/master/VMM/Templates/NC/ have the following setting <vmmst:StorageClassificationRef>Local Storage</vmmst:StorageClassificationRef> for the virtual disk
For example in:
https://github.com/Microsoft/SDN/blob/master/VMM/Templates/NC/Network%20Controller%20Production%20Generation%201%20VM.xml 
that is line 165.
Line 165 (<vmmst:StorageClassificationRef>Local Storage</vmmst:StorageClassificationRef>) should be removed.
Such setting will cause deploying to C:\ locally on a machine rather then to C:\ClusterStorage\Volume1\. In a cluster scenario this could result into deployment issue.

**Comment by JMesser81** [comment]
ping @manishmsft

**Comment by manishmsft** [comment]
Thanks for reporting this. Taking a look.

**Comment by manishmsft** [comment]
hello @slavizh , could you resolve this issue as this is now addressed. cc @JMesser81

**Comment by slavizh** [comment]
Ok. I guess you will made the changes to the templates.
