### ISSUE TITLE
SLB and Gateway VMM Templates Require MAC Spoofing Enabled

### ISSUE THREAD

**Issue by TriJetScud** [Microsoft/SDN#75]
The SCVMM 2016 Service Templates for the SLB and Gateway roles requires the option "Enable spoofing of MAC addresses" selected on NIC's that send and receive tenant data.

In our lab environment, we were unable to get the SLB and Gateway roles working right until we discovered that we need to have MAC spoofing enabled on the interfaces that send and receive tenant data.

**Comment by JMesser81** [comment]
@manishmsft

**Comment by micros01** [comment]
Can someone confirm that this is the case? We also have problems with communication from and to  tenant VM's through SLB. Unfortunately our lab environment is not up and running at the moment so I can't test this myself.

**Comment by micros01** [comment]
Hi again, I will confirm this myself since we have now been able to get our servers up to speed and done some more testing. 
We finally got this to work but we did NOT have to enable MAC Address Spoofing on any NIC to get things working. Our previous problems were most likely caused by BGP/switch problems.

**Comment by TriJetScud** [comment]
Can you tell me which patch level of Windows Server 2016 you were using in the lab environment? We've been using build 14393.571 when we were experiencing these issues.

**Comment by jefflshaffer** [comment]
Hey all.  I am working on a deployment with a customer and we are experiencing significant broadcast storm when enabling the NICs in our SLB(s).  Has anyone seen this?

**Comment by TriJetScud** [comment]
So far we haven't seen broadcast storms when we've brought up our SLB's.

**Comment by grcusanz** [comment]
MAC address spoofing should not be required as both SLB and the Gateways route packets using their assigned MAC addresses as source and destination.  As far as broadcast storms, machines that use of Microsoft Network Load Balancing (NLB) Role can cause broadcast storms and those may be amplified if placed on the same VLAN as the SLB Mux.  Our recommendation is to not share the same infrastructure VLANs between SDN infrastructure and existing NLB instances.
