### ISSUE TITLE
error on line 1132 in the onboardGateway function 'InUseVirtualServerCannotBeDeleted'

### ISSUE THREAD

**Issue by WouterLS** [Microsoft/SDN#78]
I'm getting the following error on line 1132 in the onboardGateway function.
Not sure what's going on. Somehow I'm getting this error when associating the service "gateway manager" to the gateway manager role.
Hopefully someone can help me out.

`Error (50125)
Network service threw an unhandled exception: '{
  "error": {
    "code": "InUseVirtualServerCannotBeDeleted",
    "message": "VirtualServer is being used by Gateway resource and cannot be deleted. Delete the dependent resource first and then retry.",
    "innerError": "Microsoft.WindowsAzure.Networking.Nrp.Frontend.Common.ValidationException: VirtualServer is being used by Gateway resource and cannot be deleted. Delete the dependent resource first and then retry.\r\n   at Microsoft.Windows.Networking.NetworkController.Framework.Operations.DeleteVirtualServerOperation.ExecuteInternal(VirtualServer existingResource, ITransaction transaction)\r\n   at Microsoft.Windows.Networking.NetworkController.RestApi.Common.Operations.DeleteResourceDefaultOperation`1.DefaultExecuteTopLevelResource()\r\n   at Microsoft.Windows.Networking.NetworkController.RestApi.Common.Operations.DeleteResourceDefaultOperation`1.Execute()\r\n   at Microsoft.WindowsAzure.Networking.Nrp.Frontend.Operations.OperationBase`1.Run()"
  }
}'

Recommended Action
Work with the network service vendor to fix the problem.
`

**Comment by micros01** [comment]
Hi, have the same problem. Though I'm not using the script but trying to manually add the Gateway service through VMM. Tried reinstalling everything but still same error. Still haven't been able to find out why but this stops us from continuing are tests :-/ 

Cannot find any info anywhere about this error???

**Comment by drk9999** [comment]
This happens only with the Jan. windows server update. Back to RTM to the second update in December and you will be fine.

**Comment by WouterLS** [comment]
On the VMM server or the template for the VM's that run the network controller services?

**Comment by micros01** [comment]
Hi, have now redeployed everything and skipped the Januari update on the VMM server. Trying to add Gateway to NetworkController now gives this error (at step "Associate VM with a fabric role" instead...
Anybody, help??

Error (50125)
Network service threw an unhandled exception: '{
  "error": {
    "code": "InternalServerError",
    "message": "An error occured.",
    "innerError": "System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Microsoft.Windows.Networking.NetworkController.RestApi.GetNetworkInterfacesOperation.SanitizeNetworkInterface(NetworkInterface networkInterface)\r\n   at Microsoft.Windows.Networking.NetworkController.RestApi.GetNetworkInterfaceOperation.Execute()"
  }
}'

Recommended Action
Work with the network service vendor to fix the problem.

**Comment by drk9999** [comment]
No on the VMM server it doesn't matter. Don't use images for the VMs that have the update applied. Also not applied on Hyper-V hosts.

I'm not sure which VMs can't have it applied, but when I reverted to deploying the VMs from an earlier VHDX, the error went away.

**Comment by billmclaren** [comment]
+1. Just bumped into the same error.

"VirtualServer is being used by Gateway resource and cannot be deleted. Delete the dependent resource first and then retry."

Thanks for the pointers.

**Comment by nnamuhcs** [comment]
Install the VMM UR2 will fix this issue.

**Comment by nnamuhcs** [comment]
You can get the update from here - https://support.microsoft.com/en-us/help/3209586/update-rollup-2-for-system-center-2016-virtual-machine-manager

**Comment by billmclaren** [comment]
Thanks!  Three other fixes in here that have been kicking my butt for weeks.

**Comment by micros01** [comment]
If you get ""code": "InternalServerError"," when onboarding, see this discussion here: https://github.com/Microsoft/SDN/issues/85

**Comment by JMesser81** [comment]
Re-opened as issue is not fixed with SCVMM UR2

**Comment by JMesser81** [comment]
Please email sdn_feedback@microsoft.com and someone will reach out.

**Comment by c0dybrown** [comment]
@JMesser81 Thanks for the response.

Has anyone tested this with SCVMM UR2.1?
[https://support.microsoft.com/en-us/help/4011491/update-rollup-2-1-for-system-center-2016-virtual-machine-manager](https://support.microsoft.com/en-us/help/4011491/update-rollup-2-1-for-system-center-2016-virtual-machine-manager)

And/or with KB4013429/KB4015438 installed on Server 2016 guests?
[https://support.microsoft.com/en-us/help/4015438](https://support.microsoft.com/en-us/help/4015438)

I spent several days messing around with this and don't want to set the whole environment up again if it still doesn't work, thanks.

**Comment by MikeFrith** [comment]
I've got SCVMM UR2.1 installed with KB4015438 installed on the guests and still receiving the error.

**Comment by JMesser81** [comment]
Sorry for the delay in responding, here. This issue should have been fixed in Windows Server 2016 beginning with the January update (KB4010672). I recommend you install latest monthly update (most recent as of today) https://support.microsoft.com/en-us/help/4016635 .

**Comment by JMesser81** [comment]
@MikeFrith @WouterLS @c0dybrown - Is this issue fixed with recent updates or are you still hitting the same problem? If a different message is encountered, let's close this issue and re-open a new one.

Also - we just found a bug where a VM Network cannot be deleted due to a "VirtualSubnetInUse" error message. This occurs when a stale Gateway connection fails over to a backup Gateway VM. The original Gateway connection on the previously active Gateway VM is not properly cleaned up.

**Comment by c0dybrown** [comment]
@JMesser81 thanks for your support. I tried updating all hosts involved in deployment to KB4015438 (March) with SCVMM UR2.1 and still saw the error. I have not tried with KB4016635. I will not try again until Server 2016 build 1703 is released.

**Comment by MikeFrith** [comment]
@JMesser81 I encountered this problem initially with a fully patched image. The only way I could get it to deploy correctly was to roll the image back to RTM.

**Comment by AnirbanPaul** [comment]
@MikeFrith - Have you deployed the KB 4010672. It has to be deployed on the host machines and the Network Controller VMs.

**Comment by kallie-b** [comment]
Any new progress on this issue to report?

**Comment by WouterLS** [comment]
I haven't encountered the issue anymore.

**Comment by grcusanz** [comment]
Thanks for the update, closing this issue.
