### ISSUE TITLE
Insert HTML or Picture to appointment

### ISSUE THREAD

**Issue by omergv** [Microsoft/SDN#81]
Hi,

i need to insert HTML view or picture to appointment body.
please advice me how to do it with web service or any other way.

i need to send it from my application.

Thank you,
Omer G

**Comment by kallie-b** [comment]
Hi Omer,

Could you live a little more context to your question here? This is the Microsoft Software Defined Networking repository--is that what you're looking for? 

What appointment body are you referring to? And what kind of application do you mean?

With more info I'll be happy to assist you or point you in the right direction.
--Kallie

**Comment by kallie-b** [comment]
Closing issue. If you require further assistance on this please email sdn_feedback@microsoft.com.
