### ISSUE TITLE
Failed to associate gateway VM's to the NC

### ISSUE THREAD

**Issue by erjenrijnders** [Microsoft/SDN#85]
I get this error on the very last step of the script when "add-SCFabricRoleResource" happens for the gateway VM's:

`Error (50125)
Network service threw an unhandled exception: '{
  "error": {
    "code": "InternalServerError",
    "message": "An error occured.",
    "innerError": "System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Microsoft.Windows.Networking.NetworkController.RestApi.GetNetworkInterfacesOperation.SanitizeNetworkInterface(NetworkInterface networkInterface)\r\n   at Microsoft.Windows.Networking.NetworkController.RestApi.GetNetworkInterfaceOperation.Execute()"
  }
}'

Recommended Action
Work with the network service vendor to fix the problem.`

I have installed rollup 2.1 so I am on version 4.0.2051.0 now.

Another mentioned this error also in this post: 
[https://github.com/Microsoft/SDN/issues/78](url)

I have choosen standalone, non HA gen2 settings.

Any help is much appreciated.

**Comment by kallie-b** [comment]
ping @manishmsft

**Comment by micros01** [comment]
Hi, we had this error and struggled to find the reason.
In our case It was related to a January windows update on the Gateway VM's.

Our solution was to replace the VHDX used for deploying and create a new one with 2016 RTM (no patches).
Then we redeployed the gateway VM's with this new unpatched image and the onboarding was thereafter working fine.

When finally onboarded we then patched the GW VM's fully and so far Everythings working.

We have actually offboarded and then onboarded the same GW VM's when fully patched(needed to change the "Gateway Capacity" which required offboarding) and that actually worked fine.

**Comment by erjenrijnders** [comment]
I was able to get an RTM version, but fails with the exact same error code too unfortunately :(

**Comment by AnirbanPaul** [comment]
KB4010672 has the fix for this bug. You should ensure that the Network Controller VMs get this patch.

**Comment by superdomi** [comment]
Still not working. Same error after installing KB4010672 on Gateway VM ,,,

**Comment by AnirbanPaul** [comment]
The patch has to be installed on the Network Controller VMs.

**Comment by erjenrijnders** [comment]
It works after installing this update! Thanks a lot.
I had to reboot the network controller vm's twice, after the first reboot it gave the same error.
I also rebooted the VMM server to be sure. After that, it worked fine.

**Comment by JMesser81** [comment]
Closed

**Comment by realjonas** [comment]
Have this error when trying to onboard SLB/MUX in vmm 2016
![image](https://user-images.githubusercontent.com/23555853/34270375-480c12be-e688-11e7-8543-20495e1bff50.png)
And yes I have run get-scipaddress and revoke-scipaddress but it's not reserved.
Running the latest update on all nodes
Anyone have a clue?
/j

**Comment by AnirbanPaul** [comment]
[+Sanjay, Gaurav]
