### ISSUE TITLE
SDN and VMM

### ISSUE THREAD

**Issue by superdomi** [Microsoft/SDN#88]
We successfully deployed a Network Controller infrastructure with VMM. During the setup we got no erros. The onboarding worked without any issue and the creation of new Tenant networks works perfectly. 

But we are not able to get an IP address inside a Tenant VM. Our Hosts and NCs are running the latest patches. The Debug Output from NC are showing no errors. We used the production template with 3 Nodes and a PKI certificate (not Self-Signed)

The only thing we are missing are the three established session from the Hosts to the NC. We disabled the firewalls on all servers. We see connections with the TIME_WAIT state ...

What were we missing ? Nothing inside the Host Eventvwr or trace logs. Many warning in the NC Service-Fabric EventLog. But no errors in the Network Controller EventLog.

Best regards

Dominik

**Comment by JMesser81** [comment]
@superdomi  - sorry for the delayed response on this. This appears to be an issue with your X.509 certificates on the Hyper-V Host which is preventing mutual authentication between the NC Host Agent and Network Controller . Could you check a few things for us?

From an elevated command prompt:
* [Hyper-V Host] PS C:\> dir cert:\\LocalMachine\my (Look for multiple certificates with the same subject name)
* [Machine with access to Network Controller] PS C:\> Debug-NetworkController -NetworkController <nc name> -Credential $cred

Where $cred is a user object with access to Network Controller (in NC Management Group)

Please send us the output and upload logs somewhere where we can diagnose
Thanks,
Jason

**Comment by superdomi** [comment]
Hi Jason, we've changed the certificate of the NC VMs to a Self-Signed one. Since this the NCs are working as expected. 

But I have a new problem with setting up Internet access from a tenant VM. We are using a Fortigate as our BGP router. Needs the Mgmt, HNV and Transit network to be routable through the Fortigate to each other ? Does the VM Hosts needs an IP from the Transit network ? Is it right to configure the SLB Mgmt VIP to the PrivateVIP pool ? The VM Hosts cannot access this IP and we are getting many WSAConnect errors in the LOG...

**Comment by JMesser81** [comment]
Routeability between those three networks (Mgmt, HNV, and Transit) is dependent on your physical network configuration and how your hosts are connecting to the ToRs. Can you describe your physical network infra a bit more? (e.g. how many NIC cards are you using, teaming configuration, do you have separate network adapters - or, separate SCVMM logical switch - for management, etc.)

In general, these networks can be kept separate, however, it is important that the SLB Manager VIP (usually located on the private VIP logical network) is routeable with the Management logical networks.  This is due to the fact that the Hyper-V Host's SLB Host Agent (Mgmt) requires connectivity to the SLB Manager (Private VIP). Can you verify L3 reachability from the Hyper-V Host (via Management IP address) to the SLB Manager IP address?

Only the SLB Mux VMs and Gateway VMs need to be connect to all three logical networks (Mgmt, HNV, and Transit). The Hyper-V Hosts only need to be connected to Mgmt and HNV Provider

**Comment by superdomi** [comment]
Hi Jason, our Hosts have two 10 Gbit/s NIC configured as a SET Teaming and multiple SCVMM Logical networks. The Private VIP IP address pool is only a Virtual Subnet. How can I connect the Host to this network ? How can I route to this network ?

**Comment by superdomi** [comment]
I've got to work. The Hosts can now connect to the SLB VIP IP address. But now I'm getting the following error in the SLB TraceLog of the Host:

because of Handshake failure(id: socket_error, message: socket_error: OnPartialReadComplete error code = 10060). Handshake failed 2 times.

Do I need to Import the SLB certificate to the Hosts Trusted Root ?

**Comment by JMesser81** [comment]
Did you follow this step:

_SSL certificate: To import the SLB service template you'll need to prepare an SSL certificate. You made the certificate available during network controller deployment. To use the certificate you prepared in network controller deployment for SLB, right-click the certificate and export it without a password in .CER format. Place it in the library, in the NCCertificate.CR folder you created when you set up the network controller._

SCVMM should place the cert in the correct folder where it is needed. In my case, I'm using CA-signed so the only thing in my trusted root is the CA server

**Comment by JMesser81** [comment]
However, I believe if you are using self-signed certs, you should make sure NC cert for SLB is loaded in either personal or trusted root store on each SLB Mux... double-checking on this though

**Comment by superdomi** [comment]
Ok. I will check. Can you explain how a tenant VM is accessing the internet ? Are there routed through the SLB MUX, or the Hyper-V Hosts ? Which IP address are there using to access the Internet ? I read something about DSR. We want to use the FortiGate device as the Gateway and not a seperate BGPNAT device.

**Comment by superdomi** [comment]
If I point the SLB Agent Host directly to the NC controller (modify the SLHbConfig.xml) the NAT rule seems to apply. The incoming NAT rules are working. But I cannot access the Internet. Is there physical any difference between the Public and PrivateVIP. Do I have to use an Internet routable address for the PUblicVIP ? 

Jason, thanks for your support !

**Comment by erjenrijnders** [comment]
Hi Superdomi,

Can I ask you a question about an issue that you solved yesterday, because we have exactly the same issue.

> Hi Jason, our Hosts have two 10 Gbit/s NIC configured as a SET Teaming and multiple SCVMM Logical networks. The Private VIP IP address pool is only a Virtual Subnet. How can I connect the Host to this network ? How can I route to this network ?

How did you route from the management interface to the PrivateVIP? We are stuck on this.. Would be really great if you can help us out. 

Sorry for posting between your questions..

**Comment by superdomi** [comment]
Hi erjenrijnders, you have to look on your BGP peer Router. There should be an BGB route from the Transit Network (SLB IP) to the PrivateVIP. 

We created a rule on our FortiGate to route from MGMT to the PrivateVIP. Because the FortiGate knows the Route (BGP Routing) we were able to access the PrivateVIP.

**Comment by JMesser81** [comment]
@superdomi  - you shouldn't need to modify the SLBHPCONFIG.xml file. When you deploy SLB through SCVMM and provide it with the SLB Manager VIP during configuration, it should place that VIP (from your private or public VIP logical network IP pool) in this file automatically. That IP needs to be routeable from Hyper-V Host nodes.

Yes, the Public VIP used by your NAT connections must be routeable on the Internet.

**Comment by superdomi** [comment]
Ok. And which device will route the traffic to the Internet ? SLB or Hyper-V Host ? Which IP or network will this decice use ?

**Comment by JMesser81** [comment]
@grcusanz  - who has some great slides (and maybe even a video) on how this works. 

It depends on which device initiates the connection:

**Internet => Tenant VM (e.g. Web Server)**
Ingress - Traffic destined for public VIP will be sent to SLB Mux. SLB Mux will do packet re-write (as required) and encapsulate to send it on to the tenant VM
Egress - Tenant VM will bypass mux on egress using Direct Server Return (DSR) path. SNAT operation will be applied to traffic with Source IP of Public VIP. 

**Tenant VM => Internet
In this case, I believe the same thing happens with SNAT operation applied to change Source IP to Public VIP adddress

**Comment by superdomi** [comment]
And this will only work wirh NATBGP VM or do you also support a third-party Hardware device, f.e. Our FortiGate

My problem is that I'm not able to get the tenant VM to browse the internet and I'm not seeing any traffic hitting the FortiGate.

**Comment by erjenrijnders** [comment]
Thanks Superdomi, still working on it.
@grcusanz, really looking forward to the slides and video.

**Comment by superdomi** [comment]
Any updates ? Still not able to get Internet from our tenant VM. Attached you'll find our infrastructure
[Bluearea Network.pdf](https://github.com/Microsoft/SDN/files/917946/Bluearea.Network.pdf)

**Comment by JMesser81** [comment]
@superdomi  - we do indeed support other third-party devices for BGP peering. I took a look ta your diagram and had a few questions. Perhaps we could get on a call to discuss?

**Comment by JMesser81** [comment]
One way we could understand more about what's going on in your environment is if you run the Debug-NetworkController cmdlet from a host which has access to the Network Controller.  Also, I assume you're referencing these planning docs in your deployment: https://technet.microsoft.com/en-us/windows-server-docs/networking/sdn/plan/plan-a-software-defined-network-infrastructure

**Comment by superdomi** [comment]
Hi Jason, that would be great if we can get on a call. I live in Germany, so it would be great if we can make the call at 9pm German time tomorrow ?

I read this article multiple times ! Currently we are testing Windows Servers as VM Virtual Appliance. That worls great. One NIC connected to Tenant VM network and one NIC connected to the PUBlIC IP. Configure a route inside of Network Controller and I have Internet access from my Tenant VM. But we need one Gateway for every Tenant and are not able to provide a HA Gateway.

https://technet.microsoft.com/en-us/windows-server-docs/networking/sdn/manage/use-network-virtual-appliances-on-a-vn

**Comment by JMesser81** [comment]
Yes, that would be 12:00pm our time. Could you send me an invite?

**Comment by superdomi** [comment]
Per Skype ?

powered by Bluearea





powered by Bluearea.

m+p - making progress
Hunsrückhöhenstrasse 6-8
D-56154 Boppard
T +49.6742.93117-55
Z +49.6742.93117-0
F +49.6742.93117-90
djusten@mann-partner.de <mailto:djusten@mann-partner.de>
http://www.mann-partner.de <http://www.mann-partner.de/>
________________________________
m+p GmbH & Co. KG
Geschäftsführer: Manfred Reiss und Norman Mann
Sitz: Amtsgericht Koblenz HRB 7095
________________________________

Diese Information ist ausschliesslich fuer den Adressaten bestimmt und kann vertrauliche oder gesetzlich geschuetzte Informationen enthalten. Wenn Sie nicht der bestimmungsgemaesse Adressat sind, unterrichten Sie bitte den Absender und vernichten Sie diese E-Mail. Anderen als dem bestimmungsgemaessen Adressaten ist es untersagt, diese E-Mail zu lesen, zu speichern, weiterzuleiten oder ihren Inhalt, auf welche Weise auch immer, zu verwenden. Wir verwenden aktuelle Virenschutzprogramme. Fuer Schaeden, die dem Empfaenger, gleichwohl durch von uns zugesandte mit Viren befallene E-Mails entstehen, schliessen wir jede Haftung aus.

The information contained in this email is intended only for its addressee and may contain confidential and/or privileged information. If the reader of this email is not the intended recipient, you are hereby notified that reading, saving, distribution or use of the content of this email in any way is prohibited. If you have received this email in error, please notify the sender and delete the email. We use updated antivirus protection software. We do not accept any responsibility for damages caused anyhow by viruses transmitted via email.

On Thu, Apr 13, 2017 at 4:10 PM +0200, "Jason Messer" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, that would be 12:00pm our time. Could you send me an invite?

**Comment by superdomi** [comment]
Attached you'll find our VMM Express Script.

[Fabricconfig_Bluearea.txt](https://github.com/Microsoft/SDN/files/920705/Fabricconfig_Bluearea.txt)

**Comment by kallie-b** [comment]
Ping @JMesser81 -- any updates on this?

**Comment by JMesser81** [comment]
@grcusanz is looking at this now. He is achedulimg a call

**Comment by grcusanz** [comment]
am in contact with superdomi directly on these issues. I will update once resolved.

**Comment by grcusanz** [comment]
Met with superdomi on Friday and am happy to report his issues are now resolved.

**Comment by realjonas** [comment]
Can you please porovide us vith the solution?

/J
