### ISSUE TITLE
VM Gateway and VMM SDN

### ISSUE THREAD

**Issue by superdomi** [Microsoft/SDN#89]
Hi all,

I have a another issue. After we onboarded the Gateway Service Template to the Network Controller we got the following error in Debugging Network Controller: "Gateway Cleanup failed" If we then try to remove the Service from Network Controller we are getting the error: "Network service threw an unhandled exception: 'DeleteGateway: 2837a962-a2a5-46bd-a2a4-12ec121bce4f Gateway cleanup is pending ' 

Another Thing. After onboarding the Gateway Service I get an "InfrastructurePortBlocked" if I run Debug-NetworkController on the VirtualSwitch Ressource type.

**Comment by AnirbanPaul** [comment]
Hi
Can you share the logs from %systemdrive%/Windows/tracing/SDNDiagnostics from all the Network Controller nodes.

**Comment by superdomi** [comment]
[SDNDiagnostics.zip](https://github.com/Microsoft/SDN/files/917942/SDNDiagnostics.zip)

We only have one NC in our test environments.

**Comment by kallie-b** [comment]
Ping @AnirbanPaul -- Were you able to take a look at these logs?

**Comment by grcusanz** [comment]
I am in contact with superdomi directly on these issues.  I will update once resolved.

**Comment by grcusanz** [comment]
Met with superdomi on Friday and am happy to report his issues are now resolved.

**Comment by Wawszczak** [comment]
@grcusanz could you share what was the cause? I have the same sympthoms in my environment
