### ISSUE TITLE
Single Node NC can't connect via VMM after NC Restart

### ISSUE THREAD

**Issue by sysnick** [Microsoft/SDN#92]
I have already setup my VMM\NC\SLB environment, and they worked well. I could assigned VIP to SLB Muxs and  connected the VIP to access my Back Virtual Network. To make things easier, I deployed single node NC and 3-Nodes SLB. But after I restart the NC VM, VMM can no longer connect NC. When I run "Get-NetworkControllerCluster" or "Get-NetworkContoller" in NC VM, the Command is Hung for a long time. 

I have re-deploy the environment three times. Seems I encountered the problem every time.  So, could anyone tell me where I am wrong?

**Comment by nnamuhcs** [comment]
Would you please check and share the logs from %systemdrive%/Windows/tracing/SDNDiagnostics from  the Network Controller node?

**Comment by nnamuhcs** [comment]
@sysnick hi, have you tried to use VMM SDN Express script to deploy SDN lately?

**Comment by grcusanz** [comment]
No further updates, so closing this issue.
