### ISSUE TITLE
VMM SDN Express issue

### ISSUE THREAD

**Issue by josedrivera** [Microsoft/SDN#93]
When trying to deploy either Standalone or Production using VMM SDN Express script. Script errors out after authenticating to domain. See below.

Script output:
Checking the Fabric Configuration Input Parameters
 WARNING: The product Key is blank. Specify the Product key by logging into the infrastructure VM while is it being configured
Successfully authenticated with domain System.DirectoryServices.DirectoryEntry.name
Storage Classification : System.Collections.Hashtable.StorageClassification does not exist

Any assistance would be great.

**Comment by josedrivera** [comment]
I was able to get passed this error but now script exits out after detecting VHDX. No errors or anything. .. been at this for a few days now..

**Comment by kallie-b** [comment]
@josedrivera -- Apologies for the delay on this. I'll check with my team and make sure someone follows up with you as soon as possible.

**Comment by josedrivera** [comment]
Thank you very much. 

I am stuck because I can not even deploy network controller templates standalone or production. I get this same error when it executes 1.4.1.1.1.8 of the template at invoke script command Pre-Install_3 for Application profile. 

Error (22042)
The service SDN_NC was not successfully deployed. Review the event log to determine the cause and corrective actions.

Recommended Action
The deployment can be restarted by retrying the job.


Error (22753)
The script command with properties: Type (PreInstall), Deployment Order (3) and Parent Type (ApplicationProfile), failed to complete successfully. Refer to the errors list for more information.

Recommended Action
If the script command's job restart action is set to restart, then the script will be re-executed.  Otherwise, the script command will be skipped when the job is restarted, in which case corrective action should be taken to mitigate the effects of the script command failure.


Error (22631)
The script command exit code 2148734209 matched the failure policy setting "Match any value other than zero." Standard output log data: "4648-07:00]Found certificate at path: C:\NCInstall\certificate-ssl\-Removed for posting
[2017-04-26T06:03:27.4164648-07:00]Adding certificate to personal store..
[2017-04-26T06:03:27.4945893-07:00]Saving SSL thumbprint to registry: B3-Removed for posting.
[2017-04-26T06:03:27.5727163-07:00]Retrieved SSL thumbprint from registry: B3-Removed for posting.
[2017-04-26T06:03:27.6820963-07:00]This is a single node NC Deployment
[2017-04-26T06:03:27.6820963-07:00]Checking if the computer name matches the certificate subject name
[2017-04-26T06:03:27.6820963-07:00]Adding read permission to NetworkService account
[2017-04-26T06:03:27.7289695-07:00]Caught an exception:
[2017-04-26T06:03:27.7289695-07:00]    Exception Type: System.Management.Automation.ParameterBindingValidationException
[2017-04-26T06:03:27.7445937-07:00]    Exception Message: Cannot bind argument to parameter 'Path' because it is null.
[2017-04-26T06:03:27.7445937-07:00]    Excepti"

Recommended Action
If the script command's job restart action is set to restart, then the script will be re-executed. Otherwise, the script command will be skipped when the job is restarted, in which case corrective action should be taken to mitigate the effects of the script command failure.


Error (20400)
1 parallel subtasks failed during execution.


Error (21952)
Application deployment failed for one or more tiers or application hosts in the service SDN_NC. Check job logs to get more information on the failed operation.

Recommended Action
Check error messages and retry the operation if needed.

-------------

Environment:
VMM 2016 with update 2,1
2 Windows Server 2016 Hyper-V hosts

**Comment by sanjkum** [comment]
@josedrivera This looks like a certificate issue which you are trying to use for deployment. Could you please do the following 

1. check if you have the private key file present here $ENV:ProgramData\Microsoft\Crypto\RSA\MachineKeys\* for the certificate

$privKeyCertFile = Get-Item -path "$ENV:ProgramData\Microsoft\Crypto\RSA\MachineKeys\*" | where {$_.Name -eq $targetCertPrivKey.CspKeyContainerInfo.UniqueKeyContainerName}

2. Try the deployment using selfsigned certificate. You need to name $selfsignedcert = $true in the config file of VMM express for this

**Comment by sanjkum** [comment]
@josedrivera is the CA certificate used in deployment is a *.pfx certificate and contains private key ? If not that might be the reason of failure. Please refer the following for certificate requirements:

https://technet.microsoft.com/en-us/system-center-docs/vmm/scenario/sdn-network-controller

**Comment by josedrivera** [comment]
Yes pfx with key however when I attempted to test with a similar script as you noted it came up with an error. For some reason my certificate I received from the CA was bad. I recreated the template in our CA store and was finally able to get passed that error. Now deployment finishes with out issues however when attempting to add the Network Controller Service to SCVMM and scanning the provider it will not mark "is Network Controller True". Another odd thing is on the VMs themselves they show the Network with an "!" even though they can reach the internet fully... 

Side note the initial issue was that I could not deploy SDN using the VMM SDN Express scripts. It exits the VMM SDN Express script without any errors with the only lines out-put to screen are:
---
PS C:\users\e012194\Desktop\VMM\VMM SDN Express> .\VMMExpress.ps1 -ConfigurationDataFile .\SJCSD_2.psd1 -Verbose
Getting VMM server connection with VMM server [SJVMM]
Checking the Fabric Configuration Input Parameters
 WARNING: The product Key is blank. Specify the Product key by logging into the infrastructure VM while is it being configured
Successfully authenticated with domain System.DirectoryServices.DirectoryEntry.name
 VMNetwork Name : [SDN_MGMT] 
You have decided to use CA certificate. Hope you Placed the Cert in \Templates\NC\TrustedRootCertificate.cr folder 


PackageRelease            : 
PackageResourceURI        : 
LocalPhysicalResourceData : 
PackageId                 : WinServer.vhdx
PackageName               : WinServer.vhdx
Type                      : VirtualHardDisk
ReferencedObject          : WIN2016DCSys-Prep.vhdx
IsMappedToLocalFile       : False
Description               : Windows Server with Network Controller support as a vhdx
Usage                     : {Windows Server Network Controller}




PS C:\users\e-----\Desktop\VMM\VMM SDN Express> 
---

I am so fatigue at the moment and without a log or error to reference I am lost.

I would rather use the VMM SDN Express script then manually configuring each section but it just seems every avenue I go is comes up with a brick wall.

Please if anyone can assist on this. I would greatly appreciate it. I have 2 blade chasis coming in for a new two new clusters and would love to move to SDN. 

Thanks again for everyones help :D 

-Jose

**Comment by sanjkum** [comment]
@josedrivera  the log file should be available at "\scripts\VMMExpresslogfile.log" could you please share the same.

**Comment by josedrivera** [comment]
I do not see the folder populated with any log file.

**Comment by josedrivera** [comment]
I noticed something in VMM that correlates with the time.  Which I do not understand because the configuration file is set as:  VMMLibrary="SDN Library"
___
![vmmlibrary](https://cloud.githubusercontent.com/assets/28008142/25486041/f47484f8-2b2d-11e7-9a74-61363b92034e.png)

Failed status:
Job Name: Importing physical resource "NCSetup.cr\Helper.ps1" to client. 

Error (279)
The specified path SDN Library is not valid.

Recommended Action
Select a valid path and verify the path is accessible. Try the operation again.
____

**Comment by micros01** [comment]
I got similar errors regarding VMMLibrary when using a SOFS cluster as libraryserver. Moved the share to a standalone server and then it worked.

**Comment by sanjkum** [comment]
@josedrivera  The library server input has to be path of the share, not just name ( e.g. \\machinename\Library share) Please click explore on the library share and provide the complete path. The input is library share path not name.

**Comment by josedrivera** [comment]
Ok. It finally kicked off. Not sure why but the space in my path was an issue. Lets see if it completely finishes. Thank you all for the help and guidance.

**Comment by sanjkum** [comment]
@josedrivera Please close the issue once the deployment completes.

**Comment by josedrivera** [comment]
So the deployment failed with a very general error in the sdn log...

____
Using configuration from file [.\SJCSD_2.psd1]
Getting VMM server connection with VMM server [SJVMM]
Trimmed VMName:[SJ-NCVM01.FQDN]
Recieved VMName : [SJ-NCVM01.FQDN]
VmName : [SJ-NCVM01.FQDN]
Mapping VHD to template package
Mapping NCSetup.cr to template package
Mapping ServerCertificate.cr to template package
Mapping TrustedRootCertificate.cr to template package
Starting Service Template Configuration
 getting Management Network []
Getting the service setting
Creating Account
VMName while onboarding NC : [SJ-NCVM01.FQDN]
 There is some Failure. Cleaning up the system to get in previous state...
Using configuration from file [.\SJCSD_2.psd1]
Getting VMM server connection with VMM server [SJVMM]
 Generating the self signed certificate 
Trimmed VMName:[SJ-NCVM01.FQDN]
 There is some Failure. Cleaning up the system to get in previous state...
Using configuration from file [.\SJCSD_2.psd1]
Getting VMM server connection with VMM server [SJVMM]
 Generating the self signed certificate 
Trimmed VMName:[SJ-NCVM01.FQDN]
 There is some Failure. Cleaning up the system to get in previous state...
Using configuration from file [.\SJCSD_2.psd1]
Getting VMM server connection with VMM server [SJVMM]
 Generating the self signed certificate 
Trimmed VMName:[SJ-NCVM01.FQDN]
 There is some Failure. Cleaning up the system to get in previous state...
__

However in scvmm it did successfully deployed the NC service and it seems to have error when it was attempting to add service to SCVMM Host groups received this error for the connection string.
___
Error (21426)
Execution of :: on the configuration provider  failed. Detailed exception: Unable to connect to the network service. Check connection string and network connectivity. Execution of Microsoft.SystemCenter.NetworkService::OpenDeviceConnectionEx on the configuration provider 3e2875a7-5831-4fb2-b388-1672e1c20fee failed. Detailed exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized. ---> System.ComponentModel.Win32Exception: The target principal name is incorrect
Check the documentation for the configuration provider or contact the publisher support.
Unable to connect to the network service. Check connection string and network connectivity.

Recommended Action
Check the documentation for the configuration provider or contact the publisher support.


____

All VMs were pingable as well as the Multinode FQDN prior to the script doing its cleanup/rollback. 

So I decided to run with the self sign cert thinking maybe still an issue with my CA cert and now when I start deployment with  IsCertSelfSigned =  $true  it exits after generating a self signed cert. You will also notice I tried a different prefix just in case as well. Here is the console and SDN Log output when

Console:
____
PS D:\VMM\VMM SDN Express> .\VMMExpress.ps1 -ConfigurationDataFile .\SJCSD_2.psd1 -Verbose
Getting VMM server connection with VMM server [SJVMM]
Checking the Fabric Configuration Input Parameters
 WARNING: The product Key is blank. Specify the Product key by logging into the infrastructure VM whil
e is it being configured
Successfully authenticated with domain System.DirectoryServices.DirectoryEntry.name
 VMNetwork Name : [SDN_MGMT] 
Generating Self-Signed Certificate..

PS D:\VMM\VMM SDN Express> 
___

SDN Log
___
Using configuration from file [.\SJCSD_2.psd1]
Getting VMM server connection with VMM server [SJVMM]
 Generating the self signed certificate 
Trimmed VMName:[SJ-NCVM01.FQDN]
 There is some Failure. Cleaning up the system to get in previous state...
Using configuration from file [.\SJCSD_2.psd1]
Getting VMM server connection with VMM server [SJVMM]
 Generating the self signed certificate 
Trimmed VMName:[SJCHS-NCVM01.FQDN]
 There is some Failure. Cleaning up the system to get in previous state...

**Comment by sanjkum** [comment]
@josedrivera please check the following 

1. Did the powershell execution happened in Administrator mode. It should be in Administrator mode.
2. The parameter $node.ManagementDomainFDQN in config files seems to have a value "FQDN" is it correct.
3. Did you see any error on the powershell cmd prompt.
4. Please make sure that the environment is clean and there multiple copies of Library resources are not present for example NCSetup.cr

**Comment by sanjkum** [comment]
@josedrivera are you good with SDN Deployment using VMM Express ?

**Comment by josedrivera** [comment]
I apologize. I have been out on medical leave. But in the meantime I was waiting for the network team to build out my own VLAN scheme that VMM can manage. That was done a few days ago so I am going to try again. I appreciate all the help I definitely had learned a lot!

**Comment by josedrivera** [comment]
Ok. So this is my round 2 and now I have (I believe) everything I need on the networking side completed. Now when I run the VMMExpress.ps1 it just runs and exits. Non-descriptive information. No log updates in VMM. 



Output:
__________
PS D:\VMM\VMM SDN Express> .\VMMExpress.ps1 -ConfigurationDataFile .\SJCSD.psd1 -Verbose
Getting VMM server connection with VMM server [SJVMM]

PS D:\VMM\VMM SDN Express> 
__________
 
Log file: .\scripts\VMMExpresslogfile.log
__________
Using configuration from file [.\SJCSD.psd1]
Getting VMM server connection with VMM server [SJVMM]
 There is some Failure. Cleaning up the system to get in previous state...
__________

**Comment by sanjkum** [comment]
@josedrivera could you please check if you are running VMM Express on VMM server and not on some other machine. Please check if the following cmdlet succeeds on the machine:

Get-SCVMMServer -ComputerName localhost

The problem here is the VMM Express is unable to make connection with VMM server. Please make sure that the VMM service is running and VMM Express is executed on same machine in Admin mode of Powershell session.

**Comment by sanjkum** [comment]
@josedrivera Hope your NC deployment issues are resolved. Could you please close the issue if you were able to successfully deploy NC using VMM Express.

**Comment by btnhd** [comment]
@josedrivera was this issue every resolved within your network. I'm having the same issue. Please advise. 

Thank you

**Comment by josedrivera** [comment]
I apologize for the lapse of time between responses. I am back on this project and now have all hardware needed. Trying to get a working production. Now with a new environment when I start the script it immediately exits out 

PS D:\SDN-master\SDN-master\vmm\VMM SDN Express> .\VMMExpress.ps1 -ConfigurationDataFile .\SJCSD-Fabric.psd1 -Verbose
Getting VMM server connection with VMM server [SJVMM]
Checking the Fabric Configuration Input Parameters
PS D:\SDN-master\SDN-master\vmm\VMM SDN Express>


SDN Logs - 

Using configuration from file [.\SJCSD-Fabric.psd1]
Getting VMM server connection with VMM server [SJVMM]
 There is some Failure. Cleaning up the system to get in previous state...
__________

I am full tilt in working on this and hope someone can help me with this.

**Comment by grcusanz** [comment]
@josedrivera It looks like there may be an uncaught error occurring in the checkParameters function of the script.  Can you step through it in the PowerShell ISE and narrow down which check is causing it and let us know?

**Comment by josedrivera** [comment]
How do you propose to do that?

**Comment by grcusanz** [comment]
Actually, running the ISE might not be necessary.  Instead run the following commands:

PS D:\SDN-master\SDN-master\vmm\VMM SDN Express> **$error.clear()**
PS D:\SDN-master\SDN-master\vmm\VMM SDN Express> **.\VMMExpress.ps1 -ConfigurationDataFile .\SJCSD-Fabric.psd1 -Verbose**
PS D:\SDN-master\SDN-master\vmm\VMM SDN Express> **$error**

And then share the contents of $error that are output.  That should reveal the actual exception that occurred causing the script to exit.

**Comment by josedrivera** [comment]
Wow.. wish I know that earlier.. found the issue. Was referencing an older VHD what was off a charc in the name.. Thanks for your help.. now I will try to deploy and see what happens. Seems like something is always stopping the script :(.

**Comment by sanjkum** [comment]
@josedrivera please make sure that the VHD is available in VMM library and the name of VHD is not more than 64 characters. In case the failure still persists, please share the config file so that we can guide you accordingly.

We will be enhancing the error logging in next update.

**Comment by grcusanz** [comment]
In the latest check-in I updated the logging to output the error in the final catch, so this issue should be resolved.  If you get stuck again, please file another issue.  Thanks!
