### ISSUE TITLE
PrepareNodeFornetworkController.ps1 - the term is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by WouterLS** [Microsoft/SDN#96]
I'm getting this error (in the .err file) when deploying the Network Controller. Seems to be something wrong with the patch or recent change from cmd.exe to powershell..

Hopefully someone can help.

.\PrepareNodeForNetworkController.ps1 : The term '.\PrepareNodeForNetworkController.ps1' is not 
recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:4
+ & {.\PrepareNodeForNetworkController.ps1 'LS-CLOUD\Administrator' 'Ab ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\PrepareNodeForNetworkController.ps1:String) [],  
   CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by AnirbanPaul** [comment]
This PS script is part of the SCVMM templates for deploying Network Controller. You need to import the parent folder (NCSetup.cr) to the SCVMM library as part of installing the Network Controller template. 
Link to Network Controller installation through SCVMM: https://docs.microsoft.com/en-us/system-center/vmm/sdn-controller.
Why are you trying to execute this script separately?
